// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Episode,
    Source,
    SourceStat,
    VType,
    Video
} from "./models.js";

import * as $models from "./models.js";

/**
 * FlexibleString 统一把字符串 / 数字 / null 解析为字符串。
 * 同时实现了 sql.Scanner 和 driver.Valuer，以便 SQLite 中数字/字符串都能正常读写。
 * @typedef {$models.FlexibleString} FlexibleString
 */
