// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Episode {
    /**
     * Creates a new Episode instance.
     * @param {Partial<Episode>} [$$source = {}] - The source object to create the Episode.
     */
    constructor($$source = {}) {
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_id"] = null;
        }
        if (!("ep_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ep_num"] = 0;
        }
        if (!("ep_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ep_name"] = "";
        }
        if (!("ep_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ep_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Episode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Episode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Episode(/** @type {Partial<Episode>} */($$parsedSource));
    }
}

/**
 * FlexibleString 统一把字符串 / 数字 / null 解析为字符串。
 * 同时实现了 sql.Scanner 和 driver.Valuer，以便 SQLite 中数字/字符串都能正常读写。
 * @typedef {any} FlexibleString
 */

/**
 * Source 采集源定义
 */
export class Source {
    /**
     * Creates a new Source instance.
     * @param {Partial<Source>} [$$source = {}] - The source object to create the Source.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("api_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_url"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["enabled"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 策略配置（JSON 字符串，DB 列，用于自定义数据源参数组合）
             * @member
             * @type {string | undefined}
             */
            this["strategy_config"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * === 以下为兼容旧字段（逐步废弃），读 DB 后自动展开到 AdvConfig ===
             * @member
             * @type {string | undefined}
             */
            this["url_template"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url_prefix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url_suffix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["collect_limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["collect_hours"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Source}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source(/** @type {Partial<Source>} */($$parsedSource));
    }
}

export class SourceStat {
    /**
     * Creates a new SourceStat instance.
     * @param {Partial<SourceStat>} [$$source = {}] - The source object to create the SourceStat.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("video_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["video_count"] = 0;
        }
        if (!("episode_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["episode_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceStat(/** @type {Partial<SourceStat>} */($$parsedSource));
    }
}

export class VType {
    /**
     * Creates a new VType instance.
     * @param {Partial<VType>} [$$source = {}] - The source object to create the VType.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("type_id" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["type_id"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parent_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["parent_id"] = 0;
        }
        if (!("sort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VType}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VType(/** @type {Partial<VType>} */($$parsedSource));
    }
}

export class Video {
    /**
     * Creates a new Video instance.
     * @param {Partial<Video>} [$$source = {}] - The source object to create the Video.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * 内部主键（可选，sqlite 自增）
             * @member
             * @type {number | undefined}
             */
            this["id"] = undefined;
        }
        if (!("vod_id" in $$source)) {
            /**
             * 上游资源站提供的原生视频 ID（唯一标识，用于 ON CONFLICT）
             * @member
             * @type {FlexibleString}
             */
            this["vod_id"] = null;
        }
        if (!("type_id" in $$source)) {
            /**
             * 上游资源站提供的分类 ID（用于 type 过滤）
             * @member
             * @type {FlexibleString}
             */
            this["type_id"] = null;
        }
        if (!("type_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_name"] = "";
        }
        if (!("vod_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_name"] = "";
        }
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("vod_class" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_class"] = "";
        }
        if (!("vod_lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_lang"] = "";
        }
        if (!("vod_actor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_actor"] = "";
        }
        if (!("vod_area" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_area"] = "";
        }
        if (!("vod_content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_content"] = "";
        }
        if (!("vod_pic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_pic"] = "";
        }
        if (!("vod_director" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_director"] = "";
        }
        if (!("vod_from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_from"] = "";
        }
        if (!("vod_remarks" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_remarks"] = "";
        }
        if (!("vod_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_time"] = "";
        }
        if (!("vod_year" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_year"] = "";
        }
        if (!("vod_play_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_play_url"] = "";
        }
        if (!("vod_down_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_down_url"] = "";
        }
        if (!("vod_douban_id" in $$source)) {
            /**
             * 扩展字段：豆瓣评分/热度/状态等（来自上游采集接口，不同源站可能返回数字或字符串）
             * @member
             * @type {FlexibleString}
             */
            this["vod_douban_id"] = null;
        }
        if (!("vod_douban_score" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_douban_score"] = null;
        }
        if (!("vod_hits" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_hits"] = null;
        }
        if (!("vod_hits_day" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_hits_day"] = null;
        }
        if (!("vod_hits_week" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_hits_week"] = null;
        }
        if (!("vod_hits_month" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_hits_month"] = null;
        }
        if (!("vod_pubdate" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_pubdate"] = null;
        }
        if (!("vod_version" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_version"] = null;
        }
        if (!("vod_state" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_state"] = null;
        }
        if (!("vod_score" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_score"] = null;
        }
        if (!("vod_score_all" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_score_all"] = null;
        }
        if (!("vod_score_num" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_score_num"] = null;
        }
        if (!("vod_isend" in $$source)) {
            /**
             * @member
             * @type {FlexibleString}
             */
            this["vod_isend"] = null;
        }
        if (!("vod_play_from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_play_from"] = "";
        }
        if (!("vod_play_note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_play_note"] = "";
        }
        if (!("vod_letter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_letter"] = "";
        }
        if (!("vod_tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_tag"] = "";
        }
        if (!("vod_sub" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_sub"] = "";
        }
        if (!("vod_en" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_en"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Video instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Video}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Video(/** @type {Partial<Video>} */($$parsedSource));
    }
}
