// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./app/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as douban$0 from "./app/douban/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as handler$0 from "./app/handler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./app/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<void>}
 */
export function AddFavorite(req) {
    return $Call.ByID(2305501792, req);
}

/**
 * @param {model$0.Source | null} s
 * @returns {$CancellablePromise<void>}
 */
export function AddSource(s) {
    return $Call.ByID(2907908121, s);
}

/**
 * ApplyWindowSettings 从数据库加载并应用窗口设置（启动时调用）
 * @returns {$CancellablePromise<void>}
 */
export function ApplyWindowSettings() {
    return $Call.ByID(3700789462);
}

/**
 * CancelDownload 取消一个下载任务
 * @param {string} taskId
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelDownload(taskId) {
    return $Call.ByID(2532515671, taskId);
}

/**
 * ClearAllHistory 清空全部观看历史，返回删除的条数
 * @returns {$CancellablePromise<number>}
 */
export function ClearAllHistory() {
    return $Call.ByID(232718195);
}

/**
 * ClearCache 清除指定类型的缓存
 * @param {$models.ClearCacheReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function ClearCache(req) {
    return $Call.ByID(1413834504, req);
}

/**
 * ClearLogs 删除所有日志文件
 * @returns {$CancellablePromise<number>}
 */
export function ClearLogs() {
    return $Call.ByID(1566804265);
}

/**
 * ConfirmShutdown 确认退出：触发应用退出，清理由 ServiceShutdown 统一处理
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmShutdown() {
    return $Call.ByID(2087002845);
}

/**
 * DeleteHistoryByVideo 删除某个视频的全部观看历史
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<void>}
 */
export function DeleteHistoryByVideo(req) {
    return $Call.ByID(1827235974, req);
}

/**
 * DeleteHistoryItem 删除单条观看历史
 * @param {$models.HistoryReq} req
 * @returns {$CancellablePromise<void>}
 */
export function DeleteHistoryItem(req) {
    return $Call.ByID(2090475737, req);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSource(key) {
    return $Call.ByID(2482006911, key);
}

/**
 * DeleteVideo 删除指定源中的视频（同时清理收藏和历史）
 * @param {handler$0.DeleteVideoReq} req
 * @returns {$CancellablePromise<void>}
 */
export function DeleteVideo(req) {
    return $Call.ByID(4154542665, req);
}

/**
 * DoubanDetail 获取豆瓣详情信息
 * @param {$models.DoubanDetailReq} req
 * @returns {$CancellablePromise<$models.DoubanDetailResp | null>}
 */
export function DoubanDetail(req) {
    return $Call.ByID(3249473505, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DoubanGetAll 获取全局豆瓣信息表中的记录（支持分页）
 * @param {$models.DoubanGetAllReq} req
 * @returns {$CancellablePromise<$models.DoubanGetAllResp | null>}
 */
export function DoubanGetAll(req) {
    return $Call.ByID(3566435463, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * DoubanSearch 搜索豆瓣获取 subject_id
 * @param {$models.DoubanSearchReq} req
 * @returns {$CancellablePromise<$models.DoubanSearchResp | null>}
 */
export function DoubanSearch(req) {
    return $Call.ByID(427130172, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * DoubanStatus 返回豆瓣调度器状态
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function DoubanStatus() {
    return $Call.ByID(3707256930).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DoubanTriggerNow 立即触发一次豆瓣信息补全
 * @returns {$CancellablePromise<number>}
 */
export function DoubanTriggerNow() {
    return $Call.ByID(2908978180);
}

/**
 * DoubanUpdateVideo 手动为某个视频补全豆瓣信息（搜索+解析详情，存入全局表）
 * @param {$models.DoubanUpdateVideoReq} req
 * @returns {$CancellablePromise<douban$0.DoubanInfo | null>}
 */
export function DoubanUpdateVideo(req) {
    return $Call.ByID(1029637856, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ExportSource 导出某个源的所有数据到 .json.br 文件（Brotli 压缩），返回绝对路径
 * 前端拿到文件路径后可以在系统文件管理器中复制/传给他人
 * @param {string} sourceKey
 * @returns {$CancellablePromise<string>}
 */
export function ExportSource(sourceKey) {
    return $Call.ByID(2283899518, sourceKey);
}

/**
 * FindSourcesByGlobalId 通过 global_id 查找所有拥有该视频的源
 * @param {number} globalId
 * @returns {$CancellablePromise<db$0.SourceVideoRef[]>}
 */
export function FindSourcesByGlobalId(globalId) {
    return $Call.ByID(4164783863, globalId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<(model$0.Source | null)[]>}
 */
export function GetAllSources() {
    return $Call.ByID(4208623164).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetCacheInfo 获取缓存信息
 * @returns {$CancellablePromise<$models.CacheInfo | null>}
 */
export function GetCacheInfo() {
    return $Call.ByID(1735807799).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetCloseBehavior 返回关闭行为：true=缩小到托盘，false=直接退出
 * @returns {$CancellablePromise<boolean>}
 */
export function GetCloseBehavior() {
    return $Call.ByID(1662826935);
}

/**
 * GetCollectSchedule 返回采集调度器配置与运行状态
 * @returns {$CancellablePromise<handler$0.SchedulerStatus | null>}
 */
export function GetCollectSchedule() {
    return $Call.ByID(732671778).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetCollectStatus 返回指定 source 的采集状态
 * @param {string} sourceKey
 * @returns {$CancellablePromise<handler$0.CollectStatus | null>}
 */
export function GetCollectStatus(sourceKey) {
    return $Call.ByID(1666790733, sourceKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetDownloadDir 返回默认下载目录
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadDir() {
    return $Call.ByID(2899686970);
}

/**
 * GetDownloadProgress 查询单个任务状态
 * @param {string} taskId
 * @returns {$CancellablePromise<$models.VideoDownloadStatus | null>}
 */
export function GetDownloadProgress(taskId) {
    return $Call.ByID(1305665572, taskId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<db$0.FavWithVideo[]>}
 */
export function GetFavorites(page, pageSize) {
    return $Call.ByID(1693347796, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetGlobalIdForVideo 获取指定源中某个视频的 global_id
 * @param {string} sourceKey
 * @param {string} vodId
 * @returns {$CancellablePromise<number>}
 */
export function GetGlobalIdForVideo(sourceKey, vodId) {
    return $Call.ByID(3154905735, sourceKey, vodId);
}

/**
 * GetGlobalTypes 获取所有全局类型
 * @returns {$CancellablePromise<(db$0.GlobalTypeRow | null)[]>}
 */
export function GetGlobalTypes() {
    return $Call.ByID(1792034461).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * GetLogContent 返回指定日志文件的最新内容（最多 512KB）
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function GetLogContent(filename) {
    return $Call.ByID(4287414792, filename);
}

/**
 * GetLogContentTail 返回指定日志文件的末尾 N 行内容
 * @param {string} filename
 * @param {number} tailLines
 * @returns {$CancellablePromise<string>}
 */
export function GetLogContentTail(filename, tailLines) {
    return $Call.ByID(990452922, filename, tailLines);
}

/**
 * GetLogDir 返回日志所在目录（方便前端在界面上展示"打开日志目录"）
 * @returns {$CancellablePromise<string>}
 */
export function GetLogDir() {
    return $Call.ByID(239023774);
}

/**
 * GetLogList 返回可用日志文件名列表（按时间倒序）
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogList() {
    return $Call.ByID(4031992807).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<(handler$0.HistoryItemWithVideo | null)[]>}
 */
export function GetRecentHistory(limit) {
    return $Call.ByID(3759499244, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @param {$models.RecommendReq} req
 * @returns {$CancellablePromise<(model$0.Video | null)[]>}
 */
export function GetRecommend(req) {
    return $Call.ByID(4171590299, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetSetting(key) {
    return $Call.ByID(48053349, key);
}

/**
 * GetSourceDetail 返回某个 source_key 的字段定义和示例数据
 * @param {string} sourceKey
 * @returns {$CancellablePromise<handler$0.SourceDetail | null>}
 */
export function GetSourceDetail(sourceKey) {
    return $Call.ByID(42587419, sourceKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * GetSourceParamsDoc 返回采集接口参数规范，供前端展示规则指南
 * @param {string} sourceKey
 * @returns {$CancellablePromise<handler$0.SourceParamsDoc | null>}
 */
export function GetSourceParamsDoc(sourceKey) {
    return $Call.ByID(1484335526, sourceKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @returns {$CancellablePromise<model$0.SourceStat[]>}
 */
export function GetSourceStats() {
    return $Call.ByID(1267600873).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * @param {handler$0.GetTypesReq} req
 * @returns {$CancellablePromise<(model$0.VType | null)[]>}
 */
export function GetTypes(req) {
    return $Call.ByID(3112948108, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * @param {handler$0.VideoDetailReq} req
 * @returns {$CancellablePromise<handler$0.VideoDetailResp | null>}
 */
export function GetVideoDetail(req) {
    return $Call.ByID(3080948803, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * @param {handler$0.VideoListReq} req
 * @returns {$CancellablePromise<handler$0.VideoListResp | null>}
 */
export function GetVideoList(req) {
    return $Call.ByID(643094798, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * GetWatchedEpisodes 返回指定视频已观看的所有集数
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<number[]>}
 */
export function GetWatchedEpisodes(req) {
    return $Call.ByID(70235905, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * GetYearsAndAreas 返回当前源下所有可选的年份/地区，供前端筛选下拉框使用
 * @param {string} sourceKey
 * @returns {$CancellablePromise<handler$0.YearsResp | null>}
 */
export function GetYearsAndAreas(sourceKey) {
    return $Call.ByID(2141058010, sourceKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType51($result);
    }));
}

/**
 * GracefulShutdown 优雅关闭：等待所有采集任务完成当前页后退出
 * @returns {$CancellablePromise<void>}
 */
export function GracefulShutdown() {
    return $Call.ByID(1956164136);
}

/**
 * ImportSource 从本地文件导入一个数据源（支持 .json.br / .json.gz / .json）
 * 若同名 source_key 已存在，会直接合并（Upsert 视频），由调用方先清库或删除
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function ImportSource(filePath) {
    return $Call.ByID(2199658873, filePath);
}

/**
 * ImportSourceFromBase64 从 base64 编码的文件内容导入数据源
 * 前端只能通过 FileReader 拿到 base64/ArrayBuffer，无法拿到真实文件路径，
 * 所以提供此版本绕开“路径”限制；内容支持 .json.br / .json.gz / .json
 * @param {string} filename
 * @param {string} b64Content
 * @returns {$CancellablePromise<string>}
 */
export function ImportSourceFromBase64(filename, b64Content) {
    return $Call.ByID(3831323678, filename, b64Content);
}

/**
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFavorite(req) {
    return $Call.ByID(498568789, req);
}

/**
 * IsSchedulerRunning 检查是否有调度任务正在运行（采集调度或豆瓣调度）
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSchedulerRunning() {
    return $Call.ByID(1183580401);
}

/**
 * ListDownloads 返回所有任务快照
 * @returns {$CancellablePromise<$models.VideoDownloadStatus[]>}
 */
export function ListDownloads() {
    return $Call.ByID(2520899730).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * @param {string} apiUrl
 * @param {string} sourceKey
 * @returns {$CancellablePromise<void>}
 */
export function MigrateOldData(apiUrl, sourceKey) {
    return $Call.ByID(2823894731, apiUrl, sourceKey);
}

/**
 * OpenFileInExplorer 在系统文件管理器中打开该文件（定位到文件）
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function OpenFileInExplorer(path) {
    return $Call.ByID(2722213587, path);
}

/**
 * OpenFolder 用系统文件管理器打开指定目录（便于用户拿到导出文件）
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function OpenFolder(path) {
    return $Call.ByID(3894305329, path);
}

/**
 * PauseCollect 暂停指定 source_key 的采集
 * @param {handler$0.CollectReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function PauseCollect(req) {
    return $Call.ByID(3414675569, req);
}

/**
 * PauseDownload 暂停一个下载任务
 * @param {string} taskId
 * @returns {$CancellablePromise<boolean>}
 */
export function PauseDownload(taskId) {
    return $Call.ByID(1028494649, taskId);
}

/**
 * ProxyImage 代理获取远程图片，绕过 CORS 限制
 * 返回 base64 编码的图片数据
 * @param {string} urlStr
 * @returns {$CancellablePromise<string>}
 */
export function ProxyImage(urlStr) {
    return $Call.ByID(2830726648, urlStr);
}

/**
 * RemoveDownload 从列表移除任务记录（不会删除已下载文件）
 * @param {string} taskId
 * @returns {$CancellablePromise<boolean>}
 */
export function RemoveDownload(taskId) {
    return $Call.ByID(3155670617, taskId);
}

/**
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFavorite(req) {
    return $Call.ByID(4258724909, req);
}

/**
 * RestartApp 重启应用
 * @returns {$CancellablePromise<void>}
 */
export function RestartApp() {
    return $Call.ByID(4246341431);
}

/**
 * ResumeCollect 恢复指定 source_key 的采集
 * @param {handler$0.CollectReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function ResumeCollect(req) {
    return $Call.ByID(2051635332, req);
}

/**
 * ResumeDownload 恢复一个暂停的下载任务
 * @param {string} taskId
 * @returns {$CancellablePromise<boolean>}
 */
export function ResumeDownload(taskId) {
    return $Call.ByID(687612914, taskId);
}

/**
 * RunSourceAction 统一执行数据源管理操作
 * action:
 *   - truncate       // 仅清空该源的视频/剧集/分类数据（保留 source 元信息）
 *   - recreate       // 删除并重建该源的三张表（数据全部丢失）
 *   - delete_source  // 删除该源的所有表 + sources 记录
 *   - delete_video   // 删除单条 vod_id（同时清理剧集）
 * @param {$models.SourceActionReq} req
 * @returns {$CancellablePromise<string>}
 */
export function RunSourceAction(req) {
    return $Call.ByID(1557563765, req);
}

/**
 * @param {$models.HistoryReq} req
 * @returns {$CancellablePromise<void>}
 */
export function SaveWatchHistory(req) {
    return $Call.ByID(387641349, req);
}

/**
 * SearchSource 用 wd=keyword 去指定源站模糊搜索，把结果入库，并返回
 * limit=0 时使用源的默认条数
 * @param {string} sourceKey
 * @param {string} keyword
 * @param {number} limit
 * @returns {$CancellablePromise<handler$0.SearchSourceResult | null>}
 */
export function SearchSource(sourceKey, keyword, limit) {
    return $Call.ByID(3286592348, sourceKey, keyword, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType54($result);
    }));
}

/**
 * @param {handler$0.VideoSearchReq} req
 * @returns {$CancellablePromise<handler$0.VideoListResp | null>}
 */
export function SearchVideos(req) {
    return $Call.ByID(4225132681, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * SetCloseBehavior 设置关闭行为并持久化
 * @param {boolean} minimize
 * @returns {$CancellablePromise<void>}
 */
export function SetCloseBehavior(minimize) {
    return $Call.ByID(1838468491, minimize);
}

/**
 * SetCollectSchedule 修改采集调度配置（持久化到 settings）
 * @param {handler$0.CollectScheduleConfig} cfg
 * @returns {$CancellablePromise<handler$0.CollectScheduleConfig>}
 */
export function SetCollectSchedule(cfg) {
    return $Call.ByID(3093903894, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * SetDownloadDir 设置自定义下载目录（空字符串则重置为默认）
 * @param {string} dir
 * @returns {$CancellablePromise<string>}
 */
export function SetDownloadDir(dir) {
    return $Call.ByID(3697951214, dir);
}

/**
 * SetGlobalTypeCollectEnabled 设置全局类型的采集开关
 * @param {$models.SetGlobalTypeCollectEnabledReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function SetGlobalTypeCollectEnabled(req) {
    return $Call.ByID(3501918471, req);
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(4214292049, key, value);
}

/**
 * SetSourceSchedule 设置单个源的调度配置
 * @param {handler$0.SourceScheduleReq} req
 * @returns {$CancellablePromise<void>}
 */
export function SetSourceSchedule(req) {
    return $Call.ByID(225580779, req);
}

/**
 * SetTitleBarTheme 切换标题栏主题（"dark" 或 "light"）
 * Wails 在启动时已设置 CustomTheme；这里通过 ExecJS 让系统重新应用。
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTitleBarTheme(theme) {
    return $Call.ByID(1752783553, theme);
}

/**
 * @param {handler$0.CollectReq} req
 * @returns {$CancellablePromise<handler$0.CollectStatus | null>}
 */
export function StartCollect(req) {
    return $Call.ByID(3544874275, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * StartVideoDownload 启动一个下载任务（非阻塞）
 * @param {$models.VideoDownloadReq} req
 * @returns {$CancellablePromise<$models.VideoDownloadStatus | null>}
 */
export function StartVideoDownload(req) {
    return $Call.ByID(2198607162, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * StopBackgroundCollect 停止后台循环采集，并等待短时间让状态同步
 * @returns {$CancellablePromise<boolean>}
 */
export function StopBackgroundCollect() {
    return $Call.ByID(3638107665);
}

/**
 * StopCollect 停止指定 source_key 的采集
 * @param {handler$0.CollectReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function StopCollect(req) {
    return $Call.ByID(4193761833, req);
}

/**
 * SyncGlobalTypes 从所有源同步类型到全局类型表
 * @returns {$CancellablePromise<number>}
 */
export function SyncGlobalTypes() {
    return $Call.ByID(757137074);
}

/**
 * @param {$models.TriggerCollectReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function TriggerCollectNow(req) {
    return $Call.ByID(32751937, req);
}

/**
 * @param {model$0.Source | null} s
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSource(s) {
    return $Call.ByID(948985929, s);
}

/**
 * WindowGetResizable 返回窗口是否可调整大小
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowGetResizable() {
    return $Call.ByID(2504251144);
}

/**
 * WindowGetSize 返回当前窗口尺寸
 * @returns {$CancellablePromise<$models.WindowSizeResp | null>}
 */
export function WindowGetSize() {
    return $Call.ByID(2449844830).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType57($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowIsFs() {
    return $Call.ByID(2916113086);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowIsMax() {
    return $Call.ByID(2152113913);
}

/**
 * WindowSetFullscreen 切换"系统级全屏"（覆盖任务栏，移除窗口边框）
 *   enter=true  → 进入全屏
 *   enter=false → 退出全屏
 * Wails 的 WindowFullscreen 在 Windows 上会自动移除标题栏并覆盖任务栏。
 * @param {boolean} enter
 * @returns {$CancellablePromise<void>}
 */
export function WindowSetFullscreen(enter) {
    return $Call.ByID(3706921042, enter);
}

/**
 * WindowSetResizable 设置窗口是否可拖动调整大小
 * @param {boolean} resizable
 * @returns {$CancellablePromise<void>}
 */
export function WindowSetResizable(resizable) {
    return $Call.ByID(2196154996, resizable);
}

/**
 * WindowSetSize 设置窗口尺寸
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function WindowSetSize(width, height) {
    return $Call.ByID(3415522130, width, height);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowToggleMax() {
    return $Call.ByID(1891595625);
}

/**
 * WriteLog 写入一条日志；同时记录到文件（自动按月滚动）
 * @param {$models.LogEntry} entry
 * @returns {$CancellablePromise<boolean>}
 */
export function WriteLog(entry) {
    return $Call.ByID(1800746550, entry);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.DoubanDetailResp.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.DoubanGetAllResp.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.DoubanSearchResp.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = douban$0.DoubanInfo.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = db$0.SourceVideoRef.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = model$0.Source.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.CacheInfo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = handler$0.SchedulerStatus.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = handler$0.CollectStatus.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.VideoDownloadStatus.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = db$0.FavWithVideo.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = db$0.GlobalTypeRow.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $Create.Array($Create.Any);
const $$createType28 = handler$0.HistoryItemWithVideo.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = model$0.Video.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = handler$0.SourceDetail.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = handler$0.SourceParamsDoc.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = model$0.SourceStat.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType42 = model$0.VType.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = handler$0.VideoDetailResp.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = handler$0.VideoListResp.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = $Create.Array($Create.Any);
const $$createType50 = handler$0.YearsResp.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = $Create.Array($$createType20);
const $$createType53 = handler$0.SearchSourceResult.createFrom;
const $$createType54 = $Create.Nullable($$createType53);
const $$createType55 = handler$0.CollectScheduleConfig.createFrom;
const $$createType56 = $models.WindowSizeResp.createFrom;
const $$createType57 = $Create.Nullable($$createType56);
