// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./app/db/models.js";

/**
 * CacheInfo 缓存信息
 */
export class CacheInfo {
    /**
     * Creates a new CacheInfo instance.
     * @param {Partial<CacheInfo>} [$$source = {}] - The source object to create the CacheInfo.
     */
    constructor($$source = {}) {
        if (!("local_storage_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["local_storage_bytes"] = 0;
        }
        if (!("indexed_db_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexed_db_bytes"] = 0;
        }
        if (!("database_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["database_bytes"] = 0;
        }
        if (!("database_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database_path"] = "";
        }
        if (!("disk_cache_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["disk_cache_dir"] = "";
        }
        if (!("disk_cache_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["disk_cache_bytes"] = 0;
        }
        if (!("log_file_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["log_file_bytes"] = 0;
        }
        if (!("log_file_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["log_file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CacheInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CacheInfo(/** @type {Partial<CacheInfo>} */($$parsedSource));
    }
}

/**
 * ChunkProgress 单个并发连接的分块进度
 */
export class ChunkProgress {
    /**
     * Creates a new ChunkProgress instance.
     * @param {Partial<ChunkProgress>} [$$source = {}] - The source object to create the ChunkProgress.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["end"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * 本块已下载字节数
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChunkProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChunkProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChunkProgress(/** @type {Partial<ChunkProgress>} */($$parsedSource));
    }
}

/**
 * ClearCacheReq 清除缓存请求
 */
export class ClearCacheReq {
    /**
     * Creates a new ClearCacheReq instance.
     * @param {Partial<ClearCacheReq>} [$$source = {}] - The source object to create the ClearCacheReq.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "database" | "disk_cache" | "logs" | "all"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClearCacheReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClearCacheReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClearCacheReq(/** @type {Partial<ClearCacheReq>} */($$parsedSource));
    }
}

/**
 * DoubanCommentsReq 获取豆瓣评论请求
 */
export class DoubanCommentsReq {
    /**
     * Creates a new DoubanCommentsReq instance.
     * @param {Partial<DoubanCommentsReq>} [$$source = {}] - The source object to create the DoubanCommentsReq.
     */
    constructor($$source = {}) {
        if (!("douban_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["douban_id"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("sort" in $$source)) {
            /**
             * "new_score" | "time"
             * @member
             * @type {string}
             */
            this["sort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanCommentsReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanCommentsReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanCommentsReq(/** @type {Partial<DoubanCommentsReq>} */($$parsedSource));
    }
}

/**
 * DoubanDetailReq 豆瓣详情请求
 */
export class DoubanDetailReq {
    /**
     * Creates a new DoubanDetailReq instance.
     * @param {Partial<DoubanDetailReq>} [$$source = {}] - The source object to create the DoubanDetailReq.
     */
    constructor($$source = {}) {
        if (!("subject_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanDetailReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanDetailReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanDetailReq(/** @type {Partial<DoubanDetailReq>} */($$parsedSource));
    }
}

/**
 * DoubanDetailResp 豆瓣详情响应
 */
export class DoubanDetailResp {
    /**
     * Creates a new DoubanDetailResp instance.
     * @param {Partial<DoubanDetailResp>} [$$source = {}] - The source object to create the DoubanDetailResp.
     */
    constructor($$source = {}) {
        if (!("SubjectID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SubjectID"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Rating" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Rating"] = "";
        }
        if (!("Votes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Votes"] = "";
        }
        if (!("Director" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Director"] = "";
        }
        if (!("Writer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Writer"] = "";
        }
        if (!("Actor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Actor"] = "";
        }
        if (!("Genre" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Genre"] = "";
        }
        if (!("Country" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Country"] = "";
        }
        if (!("Language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Language"] = "";
        }
        if (!("ReleaseDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ReleaseDate"] = "";
        }
        if (!("SeasonCount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SeasonCount"] = "";
        }
        if (!("EpisodeCount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EpisodeCount"] = "";
        }
        if (!("Duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Duration"] = "";
        }
        if (!("Aka" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Aka"] = "";
        }
        if (!("IMDb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["IMDb"] = "";
        }
        if (!("PosterURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PosterURL"] = "";
        }
        if (!("ShortComments" in $$source)) {
            /**
             * 短评数量
             * @member
             * @type {string}
             */
            this["ShortComments"] = "";
        }
        if (!("Hotness" in $$source)) {
            /**
             * 计算热度: votes + short_comments + 7天内新片加权
             * @member
             * @type {string}
             */
            this["Hotness"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanDetailResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanDetailResp}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanDetailResp(/** @type {Partial<DoubanDetailResp>} */($$parsedSource));
    }
}

/**
 * DoubanGetAllReq 豆瓣数据请求（支持分页）
 */
export class DoubanGetAllReq {
    /**
     * Creates a new DoubanGetAllReq instance.
     * @param {Partial<DoubanGetAllReq>} [$$source = {}] - The source object to create the DoubanGetAllReq.
     */
    constructor($$source = {}) {
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanGetAllReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanGetAllReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanGetAllReq(/** @type {Partial<DoubanGetAllReq>} */($$parsedSource));
    }
}

/**
 * DoubanGetAllResp 豆瓣数据响应（含分页信息）
 */
export class DoubanGetAllResp {
    /**
     * Creates a new DoubanGetAllResp instance.
     * @param {Partial<DoubanGetAllResp>} [$$source = {}] - The source object to create the DoubanGetAllResp.
     */
    constructor($$source = {}) {
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {(db$0.DoubanInfoRow | null)[]}
             */
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanGetAllResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanGetAllResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new DoubanGetAllResp(/** @type {Partial<DoubanGetAllResp>} */($$parsedSource));
    }
}

/**
 * DoubanSearchReq 豆瓣搜索请求
 */
export class DoubanSearchReq {
    /**
     * Creates a new DoubanSearchReq instance.
     * @param {Partial<DoubanSearchReq>} [$$source = {}] - The source object to create the DoubanSearchReq.
     */
    constructor($$source = {}) {
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanSearchReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanSearchReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanSearchReq(/** @type {Partial<DoubanSearchReq>} */($$parsedSource));
    }
}

/**
 * DoubanSearchResp 豆瓣搜索响应
 */
export class DoubanSearchResp {
    /**
     * Creates a new DoubanSearchResp instance.
     * @param {Partial<DoubanSearchResp>} [$$source = {}] - The source object to create the DoubanSearchResp.
     */
    constructor($$source = {}) {
        if (!("subject_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject_id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanSearchResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanSearchResp}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanSearchResp(/** @type {Partial<DoubanSearchResp>} */($$parsedSource));
    }
}

/**
 * DoubanUpdateVideoReq 更新单个视频的豆瓣信息请求
 */
export class DoubanUpdateVideoReq {
    /**
     * Creates a new DoubanUpdateVideoReq instance.
     * @param {Partial<DoubanUpdateVideoReq>} [$$source = {}] - The source object to create the DoubanUpdateVideoReq.
     */
    constructor($$source = {}) {
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanUpdateVideoReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanUpdateVideoReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanUpdateVideoReq(/** @type {Partial<DoubanUpdateVideoReq>} */($$parsedSource));
    }
}

export class FavReq {
    /**
     * Creates a new FavReq instance.
     * @param {Partial<FavReq>} [$$source = {}] - The source object to create the FavReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FavReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FavReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FavReq(/** @type {Partial<FavReq>} */($$parsedSource));
    }
}

export class HistoryReq {
    /**
     * Creates a new HistoryReq instance.
     * @param {Partial<HistoryReq>} [$$source = {}] - The source object to create the HistoryReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("ep_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ep_num"] = 0;
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryReq(/** @type {Partial<HistoryReq>} */($$parsedSource));
    }
}

/**
 * LogEntry 前端写入的日志条目
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("level" in $$source)) {
            /**
             * INFO / WARN / ERROR
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * 消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * 可选：来源（组件/文件）
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * 可选：详细堆栈或上下文
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * GetRecommend 返回 N 条推荐视频（会排除 excludeIds 中的 vod_id，避免"猜你喜欢"和"继续观看"重复）
 */
export class RecommendReq {
    /**
     * Creates a new RecommendReq instance.
     * @param {Partial<RecommendReq>} [$$source = {}] - The source object to create the RecommendReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("exclude_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["exclude_ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecommendReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecommendReq}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exclude_ids" in $$parsedSource) {
            $$parsedSource["exclude_ids"] = $$createField2_0($$parsedSource["exclude_ids"]);
        }
        return new RecommendReq(/** @type {Partial<RecommendReq>} */($$parsedSource));
    }
}

/**
 * SetGlobalTypeCollectEnabledReq 设置全局类型采集开关请求
 */
export class SetGlobalTypeCollectEnabledReq {
    /**
     * Creates a new SetGlobalTypeCollectEnabledReq instance.
     * @param {Partial<SetGlobalTypeCollectEnabledReq>} [$$source = {}] - The source object to create the SetGlobalTypeCollectEnabledReq.
     */
    constructor($$source = {}) {
        if (!("type_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetGlobalTypeCollectEnabledReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SetGlobalTypeCollectEnabledReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetGlobalTypeCollectEnabledReq(/** @type {Partial<SetGlobalTypeCollectEnabledReq>} */($$parsedSource));
    }
}

/**
 * GetSimilarVideos 返回同类型的相似视频（用于详情页推荐兜底）
 */
export class SimilarReq {
    /**
     * Creates a new SimilarReq instance.
     * @param {Partial<SimilarReq>} [$$source = {}] - The source object to create the SimilarReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("type_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_id"] = "";
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("exclude_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["exclude_ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimilarReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SimilarReq}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exclude_ids" in $$parsedSource) {
            $$parsedSource["exclude_ids"] = $$createField3_0($$parsedSource["exclude_ids"]);
        }
        return new SimilarReq(/** @type {Partial<SimilarReq>} */($$parsedSource));
    }
}

/**
 * SourceActionReq 前端传入的数据源操作请求
 */
export class SourceActionReq {
    /**
     * Creates a new SourceActionReq instance.
     * @param {Partial<SourceActionReq>} [$$source = {}] - The source object to create the SourceActionReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * truncate / recreate / delete_source
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * action=delete_video 时使用
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceActionReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceActionReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceActionReq(/** @type {Partial<SourceActionReq>} */($$parsedSource));
    }
}

/**
 * TriggerCollectNow 立即触发一次后台采集（不影响定时）
 * sourceKey 非空则仅采集该源；mode 可选 full/incremental/once
 */
export class TriggerCollectReq {
    /**
     * Creates a new TriggerCollectReq instance.
     * @param {Partial<TriggerCollectReq>} [$$source = {}] - The source object to create the TriggerCollectReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * full / incremental / once
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("hours" in $$source)) {
            /**
             * 增量模式的回溯小时数
             * @member
             * @type {number}
             */
            this["hours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TriggerCollectReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TriggerCollectReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TriggerCollectReq(/** @type {Partial<TriggerCollectReq>} */($$parsedSource));
    }
}

/**
 * VideoDownloadReq 前端发起的下载请求
 */
export class VideoDownloadReq {
    /**
     * Creates a new VideoDownloadReq instance.
     * @param {Partial<VideoDownloadReq>} [$$source = {}] - The source object to create the VideoDownloadReq.
     */
    constructor($$source = {}) {
        if (!("task_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["task_id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * 不含目录的文件名（含扩展名）
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("save_dir" in $$source)) {
            /**
             * 可选：自定义保存目录
             * @member
             * @type {string}
             */
            this["save_dir"] = "";
        }
        if (!("force" in $$source)) {
            /**
             * 强制覆盖已有任务（用于重复下载确认后）
             * @member
             * @type {boolean}
             */
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoDownloadReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoDownloadReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoDownloadReq(/** @type {Partial<VideoDownloadReq>} */($$parsedSource));
    }
}

/**
 * VideoDownloadStatus 下载状态（用于 GetDownloadProgress 与事件推送）
 */
export class VideoDownloadStatus {
    /**
     * Creates a new VideoDownloadStatus instance.
     * @param {Partial<VideoDownloadStatus>} [$$source = {}] - The source object to create the VideoDownloadStatus.
     */
    constructor($$source = {}) {
        if (!("task_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["task_id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("save_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["save_path"] = "";
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("downloaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloaded"] = 0;
        }
        if (!("speed_bps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed_bps"] = 0;
        }
        if (!("eta_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["eta_sec"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * queued / downloading / done / error / cancelled
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("start_time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start_time"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["end_time"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 多连接并行下载的每个分块进度
             * @member
             * @type {ChunkProgress[] | undefined}
             */
            this["chunks"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoDownloadStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoDownloadStatus}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chunks" in $$parsedSource) {
            $$parsedSource["chunks"] = $$createField12_0($$parsedSource["chunks"]);
        }
        return new VideoDownloadStatus(/** @type {Partial<VideoDownloadStatus>} */($$parsedSource));
    }
}

/**
 * WindowSizeResp 窗口尺寸响应
 */
export class WindowSizeResp {
    /**
     * Creates a new WindowSizeResp instance.
     * @param {Partial<WindowSizeResp>} [$$source = {}] - The source object to create the WindowSizeResp.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowSizeResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowSizeResp}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowSizeResp(/** @type {Partial<WindowSizeResp>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = db$0.DoubanInfoRow.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = ChunkProgress.createFrom;
const $$createType5 = $Create.Array($$createType4);
