// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ArchiveInfo 描述一个可恢复的迁移归档。
 */
export class ArchiveInfo {
    /**
     * Creates a new ArchiveInfo instance.
     * @param {Partial<ArchiveInfo>} [$$source = {}] - The source object to create the ArchiveInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("modified_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modified_at"] = "";
        }
        if (!("size_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArchiveInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchiveInfo(/** @type {Partial<ArchiveInfo>} */($$parsedSource));
    }
}

/**
 * Result 是一次导入的逐类计数，界面按这些数字讲结果，不翻译后端文案。
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("settings_applied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["settings_applied"] = 0;
        }
        if (!("settings_skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["settings_skipped"] = 0;
        }
        if (!("sources_added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sources_added"] = 0;
        }
        if (!("sources_skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sources_skipped"] = 0;
        }
        if (!("meta_applied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["meta_applied"] = 0;
        }
        if (!("favorites_added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["favorites_added"] = 0;
        }
        if (!("favorites_skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["favorites_skipped"] = 0;
        }
        if (!("history_applied" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["history_applied"] = 0;
        }
        if (!("history_skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["history_skipped"] = 0;
        }
        if (!("unresolved" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unresolved"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}
