// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Row 是一块 Go 侧进程内缓存的读数。键（detail/chart/comments/match）是给界面查文案用的
 * 稳定标识，不是中文标题——文案由前端 i18n 出，中英才可能对得上。
 * 
 * 只统计「我们自己的」缓存：前端那几块（TS 片段、海报、图片代理）只有浏览器知道命中没有，
 * 由界面自己报，所以这里的出网计数看不见它们。
 */
export class Row {
    /**
     * Creates a new Row instance.
     * @param {Partial<Row>} [$$source = {}] - The source object to create the Row.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entries"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("hits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hits"] = 0;
        }
        if (!("stale_hits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stale_hits"] = 0;
        }
        if (!("misses" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["misses"] = 0;
        }
        if (!("fetch_ok" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetch_ok"] = 0;
        }
        if (!("fetch_fail" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetch_fail"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Row instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Row}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Row(/** @type {Partial<Row>} */($$parsedSource));
    }
}
