// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tls$0 from "../../crypto/tls/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../../io/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as multipart$0 from "../../mime/multipart/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as url$0 from "../url/models.js";

/**
 * A Header represents the key-value pairs in an HTTP header.
 * 
 * The keys should be in canonical form, as returned by
 * [CanonicalHeaderKey].
 * @typedef {{ [_ in string]?: string[] }} Header
 */

/**
 * A Request represents an HTTP request received by a server
 * or to be sent by a client.
 * 
 * The field semantics differ slightly between client and server
 * usage. In addition to the notes on the fields below, see the
 * documentation for [Request.Write] and [RoundTripper].
 */
export class Request {
    /**
     * Creates a new Request instance.
     * @param {Partial<Request>} [$$source = {}] - The source object to create the Request.
     */
    constructor($$source = {}) {
        if (!("Method" in $$source)) {
            /**
             * Method specifies the HTTP method (GET, POST, PUT, etc.).
             * For client requests, an empty string means GET.
             * @member
             * @type {string}
             */
            this["Method"] = "";
        }
        if (!("URL" in $$source)) {
            /**
             * URL specifies either the URI being requested (for server
             * requests) or the URL to access (for client requests).
             * 
             * For server requests, the URL is parsed from the URI
             * supplied on the Request-Line as stored in RequestURI.  For
             * most requests, fields other than Path and RawQuery will be
             * empty. (See RFC 7230, Section 5.3)
             * 
             * For client requests, the URL's Host specifies the server to
             * connect to, while the Request's Host field optionally
             * specifies the Host header value to send in the HTTP
             * request.
             * @member
             * @type {url$0.URL | null}
             */
            this["URL"] = null;
        }
        if (!("Proto" in $$source)) {
            /**
             * The protocol version for incoming server requests.
             * 
             * For client requests, these fields are ignored. The HTTP
             * client code always uses either HTTP/1.1 or HTTP/2.
             * See the docs on Transport for details.
             * "HTTP/1.0"
             * @member
             * @type {string}
             */
            this["Proto"] = "";
        }
        if (!("ProtoMajor" in $$source)) {
            /**
             * 1
             * @member
             * @type {number}
             */
            this["ProtoMajor"] = 0;
        }
        if (!("ProtoMinor" in $$source)) {
            /**
             * 0
             * @member
             * @type {number}
             */
            this["ProtoMinor"] = 0;
        }
        if (!("Header" in $$source)) {
            /**
             * Header contains the request header fields either received
             * by the server or to be sent by the client.
             * 
             * If a server received a request with header lines,
             * 
             * 	Host: example.com
             * 	accept-encoding: gzip, deflate
             * 	Accept-Language: en-us
             * 	fOO: Bar
             * 	foo: two
             * 
             * then
             * 
             * 	Header = map[string][]string{
             * 		"Accept-Encoding": {"gzip, deflate"},
             * 		"Accept-Language": {"en-us"},
             * 		"Foo": {"Bar", "two"},
             * 	}
             * 
             * For incoming requests, the Host header is promoted to the
             * Request.Host field and removed from the Header map.
             * 
             * HTTP defines that header names are case-insensitive. The
             * request parser implements this by using CanonicalHeaderKey,
             * making the first character and any characters following a
             * hyphen uppercase and the rest lowercase.
             * 
             * For client requests, certain headers such as Content-Length
             * and Connection are automatically written when needed and
             * values in Header may be ignored. See the documentation
             * for the Request.Write method.
             * @member
             * @type {Header}
             */
            this["Header"] = {};
        }
        if (!("Body" in $$source)) {
            /**
             * Body is the request's body.
             * 
             * For client requests, a nil body means the request has no
             * body, such as a GET request. The HTTP Client's Transport
             * is responsible for calling the Close method.
             * 
             * For server requests, the Request Body is always non-nil
             * but will return EOF immediately when no body is present.
             * The Server will close the request body. The ServeHTTP
             * Handler does not need to.
             * 
             * Body must allow Read to be called concurrently with Close.
             * In particular, calling Close should unblock a Read waiting
             * for input.
             * @member
             * @type {io$0.ReadCloser}
             */
            this["Body"] = null;
        }
        if (!("GetBody" in $$source)) {
            /**
             * GetBody defines an optional func to return a new copy of
             * Body. It is used for client requests when a redirect requires
             * reading the body more than once. Use of GetBody still
             * requires setting Body.
             * 
             * For server requests, it is unused.
             * @member
             * @type {any}
             */
            this["GetBody"] = null;
        }
        if (!("ContentLength" in $$source)) {
            /**
             * ContentLength records the length of the associated content.
             * The value -1 indicates that the length is unknown.
             * Values >= 0 indicate that the given number of bytes may
             * be read from Body.
             * 
             * For client requests, a value of 0 with a non-nil Body is
             * also treated as unknown.
             * @member
             * @type {number}
             */
            this["ContentLength"] = 0;
        }
        if (!("TransferEncoding" in $$source)) {
            /**
             * TransferEncoding lists the transfer encodings from outermost to
             * innermost. An empty list denotes the "identity" encoding.
             * TransferEncoding can usually be ignored; chunked encoding is
             * automatically added and removed as necessary when sending and
             * receiving requests.
             * @member
             * @type {string[]}
             */
            this["TransferEncoding"] = [];
        }
        if (!("Close" in $$source)) {
            /**
             * Close indicates whether to close the connection after
             * replying to this request (for servers) or after sending this
             * request and reading its response (for clients).
             * 
             * For server requests, the HTTP server handles this automatically
             * and this field is not needed by Handlers.
             * 
             * For client requests, setting this field prevents re-use of
             * TCP connections between requests to the same hosts, as if
             * Transport.DisableKeepAlives were set.
             * @member
             * @type {boolean}
             */
            this["Close"] = false;
        }
        if (!("Host" in $$source)) {
            /**
             * For server requests, Host specifies the host on which the
             * URL is sought. For HTTP/1 (per RFC 7230, section 5.4), this
             * is either the value of the "Host" header or the host name
             * given in the URL itself. For HTTP/2, it is the value of the
             * ":authority" pseudo-header field.
             * It may be of the form "host:port". For international domain
             * names, Host may be in Punycode or Unicode form. Use
             * golang.org/x/net/idna to convert it to either format if
             * needed.
             * To prevent DNS rebinding attacks, server Handlers should
             * validate that the Host header has a value for which the
             * Handler considers itself authoritative. The included
             * ServeMux supports patterns registered to particular host
             * names and thus protects its registered Handlers.
             * 
             * For client requests, Host optionally overrides the Host
             * header to send. If empty, the Request.Write method uses
             * the value of URL.Host. Host may contain an international
             * domain name.
             * @member
             * @type {string}
             */
            this["Host"] = "";
        }
        if (!("Form" in $$source)) {
            /**
             * Form contains the parsed form data, including both the URL
             * field's query parameters and the PATCH, POST, or PUT form data.
             * This field is only available after ParseForm is called.
             * The HTTP client ignores Form and uses Body instead.
             * @member
             * @type {url$0.Values}
             */
            this["Form"] = {};
        }
        if (!("PostForm" in $$source)) {
            /**
             * PostForm contains the parsed form data from PATCH, POST
             * or PUT body parameters.
             * 
             * This field is only available after ParseForm is called.
             * The HTTP client ignores PostForm and uses Body instead.
             * @member
             * @type {url$0.Values}
             */
            this["PostForm"] = {};
        }
        if (!("MultipartForm" in $$source)) {
            /**
             * MultipartForm is the parsed multipart form, including file uploads.
             * This field is only available after ParseMultipartForm is called.
             * The HTTP client ignores MultipartForm and uses Body instead.
             * @member
             * @type {multipart$0.Form | null}
             */
            this["MultipartForm"] = null;
        }
        if (!("Trailer" in $$source)) {
            /**
             * Trailer specifies additional headers that are sent after the request
             * body.
             * 
             * For server requests, the Trailer map initially contains only the
             * trailer keys, with nil values. (The client declares which trailers it
             * will later send.)  While the handler is reading from Body, it must
             * not reference Trailer. After reading from Body returns EOF, Trailer
             * can be read again and will contain non-nil values, if they were sent
             * by the client.
             * 
             * For client requests, Trailer must be initialized to a map containing
             * the trailer keys to later send. The values may be nil or their final
             * values. The ContentLength must be 0 or -1, to send a chunked request.
             * After the HTTP request is sent the map values can be updated while
             * the request body is read. Once the body returns EOF, the caller must
             * not mutate Trailer.
             * 
             * Few HTTP clients, servers, or proxies support HTTP trailers.
             * @member
             * @type {Header}
             */
            this["Trailer"] = {};
        }
        if (!("RemoteAddr" in $$source)) {
            /**
             * RemoteAddr allows HTTP servers and other software to record
             * the network address that sent the request, usually for
             * logging. This field is not filled in by ReadRequest and
             * has no defined format. The HTTP server in this package
             * sets RemoteAddr to an "IP:port" address before invoking a
             * handler.
             * This field is ignored by the HTTP client.
             * @member
             * @type {string}
             */
            this["RemoteAddr"] = "";
        }
        if (!("RequestURI" in $$source)) {
            /**
             * RequestURI is the unmodified request-target of the
             * Request-Line (RFC 7230, Section 3.1.1) as sent by the client
             * to a server. Usually the URL field should be used instead.
             * It is an error to set this field in an HTTP client request.
             * @member
             * @type {string}
             */
            this["RequestURI"] = "";
        }
        if (!("TLS" in $$source)) {
            /**
             * TLS allows HTTP servers and other software to record
             * information about the TLS connection on which the request
             * was received. This field is not filled in by ReadRequest.
             * The HTTP server in this package sets the field for
             * TLS-enabled connections before invoking a handler;
             * otherwise it leaves the field nil.
             * This field is ignored by the HTTP client.
             * @member
             * @type {tls$0.ConnectionState | null}
             */
            this["TLS"] = null;
        }
        if (!("Cancel" in $$source)) {
            /**
             * Cancel is an optional channel whose closure indicates that the client
             * request should be regarded as canceled. Not all implementations of
             * RoundTripper may support Cancel.
             * 
             * For server requests, this field is not applicable.
             * 
             * Deprecated: Set the Request's context with NewRequestWithContext
             * instead. If a Request's Cancel field and context are both
             * set, it is undefined whether Cancel is respected.
             * @member
             * @type {any}
             */
            this["Cancel"] = null;
        }
        if (!("Response" in $$source)) {
            /**
             * Response is the redirect response which caused this request
             * to be created. This field is only populated during client
             * redirects.
             * @member
             * @type {Response | null}
             */
            this["Response"] = null;
        }
        if (!("Pattern" in $$source)) {
            /**
             * Pattern is the [ServeMux] pattern that matched the request.
             * It is empty if the request was not matched against a pattern.
             * @member
             * @type {string}
             */
            this["Pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Request}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        const $$createField12_0 = $$createType5;
        const $$createField13_0 = $$createType5;
        const $$createField14_0 = $$createType7;
        const $$createField15_0 = $$createType2;
        const $$createField18_0 = $$createType9;
        const $$createField20_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("URL" in $$parsedSource) {
            $$parsedSource["URL"] = $$createField1_0($$parsedSource["URL"]);
        }
        if ("Header" in $$parsedSource) {
            $$parsedSource["Header"] = $$createField5_0($$parsedSource["Header"]);
        }
        if ("TransferEncoding" in $$parsedSource) {
            $$parsedSource["TransferEncoding"] = $$createField9_0($$parsedSource["TransferEncoding"]);
        }
        if ("Form" in $$parsedSource) {
            $$parsedSource["Form"] = $$createField12_0($$parsedSource["Form"]);
        }
        if ("PostForm" in $$parsedSource) {
            $$parsedSource["PostForm"] = $$createField13_0($$parsedSource["PostForm"]);
        }
        if ("MultipartForm" in $$parsedSource) {
            $$parsedSource["MultipartForm"] = $$createField14_0($$parsedSource["MultipartForm"]);
        }
        if ("Trailer" in $$parsedSource) {
            $$parsedSource["Trailer"] = $$createField15_0($$parsedSource["Trailer"]);
        }
        if ("TLS" in $$parsedSource) {
            $$parsedSource["TLS"] = $$createField18_0($$parsedSource["TLS"]);
        }
        if ("Response" in $$parsedSource) {
            $$parsedSource["Response"] = $$createField20_0($$parsedSource["Response"]);
        }
        return new Request(/** @type {Partial<Request>} */($$parsedSource));
    }
}

/**
 * Response represents the response from an HTTP request.
 * 
 * The [Client] and [Transport] return Responses from servers once
 * the response headers have been received. The response body
 * is streamed on demand as the Body field is read.
 */
export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("Status" in $$source)) {
            /**
             * e.g. "200 OK"
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("StatusCode" in $$source)) {
            /**
             * e.g. 200
             * @member
             * @type {number}
             */
            this["StatusCode"] = 0;
        }
        if (!("Proto" in $$source)) {
            /**
             * e.g. "HTTP/1.0"
             * @member
             * @type {string}
             */
            this["Proto"] = "";
        }
        if (!("ProtoMajor" in $$source)) {
            /**
             * e.g. 1
             * @member
             * @type {number}
             */
            this["ProtoMajor"] = 0;
        }
        if (!("ProtoMinor" in $$source)) {
            /**
             * e.g. 0
             * @member
             * @type {number}
             */
            this["ProtoMinor"] = 0;
        }
        if (!("Header" in $$source)) {
            /**
             * Header maps header keys to values. If the response had multiple
             * headers with the same key, they may be concatenated, with comma
             * delimiters.  (RFC 7230, section 3.2.2 requires that multiple headers
             * be semantically equivalent to a comma-delimited sequence.) When
             * Header values are duplicated by other fields in this struct (e.g.,
             * ContentLength, TransferEncoding, Trailer), the field values are
             * authoritative.
             * 
             * Keys in the map are canonicalized (see CanonicalHeaderKey).
             * @member
             * @type {Header}
             */
            this["Header"] = {};
        }
        if (!("Body" in $$source)) {
            /**
             * Body represents the response body.
             * 
             * The response body is streamed on demand as the Body field
             * is read. If the network connection fails or the server
             * terminates the response, Body.Read calls return an error.
             * 
             * The http Client and Transport guarantee that Body is always
             * non-nil, even on responses without a body or responses with
             * a zero-length body. It is the caller's responsibility to
             * close Body. The default HTTP client's Transport may not
             * reuse HTTP/1.x "keep-alive" TCP connections if the Body is
             * not read to completion and closed.
             * 
             * The Body is automatically dechunked if the server replied
             * with a "chunked" Transfer-Encoding.
             * 
             * As of Go 1.12, the Body will also implement io.Writer
             * on a successful "101 Switching Protocols" response,
             * as used by WebSockets and HTTP/2's "h2c" mode.
             * @member
             * @type {io$0.ReadCloser}
             */
            this["Body"] = null;
        }
        if (!("ContentLength" in $$source)) {
            /**
             * ContentLength records the length of the associated content. The
             * value -1 indicates that the length is unknown. Unless Request.Method
             * is "HEAD", values >= 0 indicate that the given number of bytes may
             * be read from Body.
             * @member
             * @type {number}
             */
            this["ContentLength"] = 0;
        }
        if (!("TransferEncoding" in $$source)) {
            /**
             * Contains transfer encodings from outer-most to inner-most. Value is
             * nil, means that "identity" encoding is used.
             * @member
             * @type {string[]}
             */
            this["TransferEncoding"] = [];
        }
        if (!("Close" in $$source)) {
            /**
             * Close records whether the header directed that the connection be
             * closed after reading Body. The value is advice for clients: neither
             * ReadResponse nor Response.Write ever closes a connection.
             * @member
             * @type {boolean}
             */
            this["Close"] = false;
        }
        if (!("Uncompressed" in $$source)) {
            /**
             * Uncompressed reports whether the response was sent compressed but
             * was decompressed by the http package. When true, reading from
             * Body yields the uncompressed content instead of the compressed
             * content actually set from the server, ContentLength is set to -1,
             * and the "Content-Length" and "Content-Encoding" fields are deleted
             * from the responseHeader. To get the original response from
             * the server, set Transport.DisableCompression to true.
             * @member
             * @type {boolean}
             */
            this["Uncompressed"] = false;
        }
        if (!("Trailer" in $$source)) {
            /**
             * Trailer maps trailer keys to values in the same
             * format as Header.
             * 
             * The Trailer initially contains only nil values, one for
             * each key specified in the server's "Trailer" header
             * value. Those values are not added to Header.
             * 
             * Trailer must not be accessed concurrently with Read calls
             * on the Body.
             * 
             * After Body.Read has returned io.EOF, Trailer will contain
             * any trailer values sent by the server.
             * @member
             * @type {Header}
             */
            this["Trailer"] = {};
        }
        if (!("Request" in $$source)) {
            /**
             * Request is the request that was sent to obtain this Response.
             * Request's Body is nil (having already been consumed).
             * This is only populated for Client requests.
             * @member
             * @type {Request | null}
             */
            this["Request"] = null;
        }
        if (!("TLS" in $$source)) {
            /**
             * TLS contains information about the TLS connection on which the
             * response was received. It is nil for unencrypted responses.
             * The pointer is shared between responses and should not be
             * modified.
             * @member
             * @type {tls$0.ConnectionState | null}
             */
            this["TLS"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        const $$createField8_0 = $$createType3;
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType13;
        const $$createField13_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Header" in $$parsedSource) {
            $$parsedSource["Header"] = $$createField5_0($$parsedSource["Header"]);
        }
        if ("TransferEncoding" in $$parsedSource) {
            $$parsedSource["TransferEncoding"] = $$createField8_0($$parsedSource["TransferEncoding"]);
        }
        if ("Trailer" in $$parsedSource) {
            $$parsedSource["Trailer"] = $$createField11_0($$parsedSource["Trailer"]);
        }
        if ("Request" in $$parsedSource) {
            $$parsedSource["Request"] = $$createField12_0($$parsedSource["Request"]);
        }
        if ("TLS" in $$parsedSource) {
            $$parsedSource["TLS"] = $$createField13_0($$parsedSource["TLS"]);
        }
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}

/**
 * A ResponseWriter interface is used by an HTTP handler to
 * construct an HTTP response.
 * 
 * A ResponseWriter may not be used after [Handler.ServeHTTP] has returned.
 * @typedef {any} ResponseWriter
 */

// Private type creation functions
const $$createType0 = url$0.URL.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
var $$createType2 = /** @type {(...args: any[]) => any} */(function $$initCreateType2(...args) {
    if ($$createType2 === $$initCreateType2) {
        $$createType2 = $$createType4;
    }
    return $$createType2(...args);
});
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
var $$createType5 = /** @type {(...args: any[]) => any} */(function $$initCreateType5(...args) {
    if ($$createType5 === $$initCreateType5) {
        $$createType5 = $$createType4;
    }
    return $$createType5(...args);
});
const $$createType6 = multipart$0.Form.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = tls$0.ConnectionState.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = Response.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = Request.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
