// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * Adapter 是 kind=source 包里的一个采集适配条目（docs/plugins.md §3）。
 */
export class Adapter {
    /**
     * Creates a new Adapter instance.
     * @param {Partial<Adapter>} [$$source = {}] - The source object to create the Adapter.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["name"] = {};
        }
        if (!("strategy" in $$source)) {
            /**
             * Strategy 是包里的 strategy 文档，已按 source-strategy-v2 schema 校验过形状，
             * 原样转给界面写进 sources.strategy_config。
             * @member
             * @type {json$0.RawMessage}
             */
            this["strategy"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Adapter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Adapter}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField1_0($$parsedSource["name"]);
        }
        return new Adapter(/** @type {Partial<Adapter>} */($$parsedSource));
    }
}

/**
 * Info 是扫描结果，也是 Wails 绑定直接交给前端的结构，字段名即 JSON 契约。
 */
export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["name"] = {};
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["description"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * Author 来自 manifest，只用于展示：扩展包是第三方内容，界面要能看出是谁写的。
             * @member
             * @type {string | undefined}
             */
            this["author"] = undefined;
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }
        if (!("reason_code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason_code"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Source / Shader / Theme 恰好一个非 nil，与 Kind 对应；Status=="invalid" 时三个都是 nil。
             * Script 是横切段：任何 kind 都可以带，kind=script 时它是唯一的那一节。
             * @member
             * @type {SourceSection | null | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ShaderSection | null | undefined}
             */
            this["shader"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ThemeSection | null | undefined}
             */
            this["theme"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScriptSection | null | undefined}
             */
            this["script"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Icon 是 manifest 声明的包内相对图标路径，已校验存在、扩展名合法、够小。
             * 界面用 ReadAsset(id, icon) 取它；空串表示这个包没提供图标。
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (!("files" in $$source)) {
            /**
             * Files / Bytes / Updated 是扫描时从包目录实际数出来的，不来自 manifest：
             * 包就是用户自己放进去的一个文件夹，界面得能说出里面有多少东西、最后一次
             * 改动是什么时候——那是判断「我刚改的文件生效了没有」唯一诚实的依据。
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updated"] = undefined;
        }
        if (!("builtin" in $$source)) {
            /**
             * Builtin 标记「这个包是应用自带的」（app/plugin/builtin/ 里那批）。界面据此
             * 决定给不给卸载按钮：删掉别人的包是卸载，删应用自己的东西不是。
             * @member
             * @type {boolean}
             */
            this["builtin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType4;
        const $$createField12_0 = $$createType6;
        const $$createField13_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField3_0($$parsedSource["name"]);
        }
        if ("description" in $$parsedSource) {
            $$parsedSource["description"] = $$createField4_0($$parsedSource["description"]);
        }
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField10_0($$parsedSource["source"]);
        }
        if ("shader" in $$parsedSource) {
            $$parsedSource["shader"] = $$createField11_0($$parsedSource["shader"]);
        }
        if ("theme" in $$parsedSource) {
            $$parsedSource["theme"] = $$createField12_0($$parsedSource["theme"]);
        }
        if ("script" in $$parsedSource) {
            $$parsedSource["script"] = $$createField13_0($$parsedSource["script"]);
        }
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}

/**
 * ScriptSection 对应 manifest 的 script 段：前端注入的入口脚本与样式表。
 * 路径都是包内相对路径，校验时已确认存在、扩展名合法且没越出包目录；
 * 内容不在这里读——前端拿 ReadPluginFile(id, entry) 取源码，好让重扫之后不缓存旧代码。
 */
export class ScriptSection {
    /**
     * Creates a new ScriptSection instance.
     * @param {Partial<ScriptSection>} [$$source = {}] - The source object to create the ScriptSection.
     */
    constructor($$source = {}) {
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["styles"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptSection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptSection}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("styles" in $$parsedSource) {
            $$parsedSource["styles"] = $$createField1_0($$parsedSource["styles"]);
        }
        return new ScriptSection(/** @type {Partial<ScriptSection>} */($$parsedSource));
    }
}

/**
 * ShaderEntry 是 kind=shader 包里的一个自定义档位（docs/plugins.md §4）。
 */
export class ShaderEntry {
    /**
     * Creates a new ShaderEntry instance.
     * @param {Partial<ShaderEntry>} [$$source = {}] - The source object to create the ShaderEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["name"] = {};
        }
        if (!("entry" in $$source)) {
            /**
             * 包内相对路径，已校验确实存在
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }
        if (!("scale" in $$source)) {
            /**
             * 1 或 2
             * @member
             * @type {number}
             */
            this["scale"] = 0;
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShaderEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShaderEntry}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField1_0($$parsedSource["name"]);
        }
        return new ShaderEntry(/** @type {Partial<ShaderEntry>} */($$parsedSource));
    }
}

/**
 * ShaderSection 对应 manifest 的 shader 段：单个对象与 shaders 数组都归一化到这里。
 */
export class ShaderSection {
    /**
     * Creates a new ShaderSection instance.
     * @param {Partial<ShaderSection>} [$$source = {}] - The source object to create the ShaderSection.
     */
    constructor($$source = {}) {
        if (!("shaders" in $$source)) {
            /**
             * @member
             * @type {ShaderEntry[]}
             */
            this["shaders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShaderSection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShaderSection}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shaders" in $$parsedSource) {
            $$parsedSource["shaders"] = $$createField0_0($$parsedSource["shaders"]);
        }
        return new ShaderSection(/** @type {Partial<ShaderSection>} */($$parsedSource));
    }
}

/**
 * SourceSection 对应 manifest 的 source 段。
 */
export class SourceSection {
    /**
     * Creates a new SourceSection instance.
     * @param {Partial<SourceSection>} [$$source = {}] - The source object to create the SourceSection.
     */
    constructor($$source = {}) {
        if (!("adapters" in $$source)) {
            /**
             * @member
             * @type {Adapter[]}
             */
            this["adapters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceSection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceSection}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("adapters" in $$parsedSource) {
            $$parsedSource["adapters"] = $$createField0_0($$parsedSource["adapters"]);
        }
        return new SourceSection(/** @type {Partial<SourceSection>} */($$parsedSource));
    }
}

/**
 * Status 是注册表里每个包的三种状态之一（docs/plugins.md §2）。
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusReady: "ready",
    StatusDisabled: "disabled",
    StatusInvalid: "invalid",
};

/**
 * ThemePreset 是校验通过的主题预设（docs/plugins.md §5）。
 */
export class ThemePreset {
    /**
     * Creates a new ThemePreset instance.
     * @param {Partial<ThemePreset>} [$$source = {}] - The source object to create the ThemePreset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["name"] = {};
        }
        if (!("primary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["primary"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["tint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * BGImage 是包内相对路径（已校验存在且没越界）；界面用 Service.ReadAsset(Info.ID, BGImage) 取图。
             * @member
             * @type {string | undefined}
             */
            this["bg_image"] = undefined;
        }
        if (!("pack" in $$source)) {
            /**
             * Pack 是归属的扩展包 id，读包内文件时要用它定位目录。
             * @member
             * @type {string}
             */
            this["pack"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemePreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemePreset}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField1_0($$parsedSource["name"]);
        }
        if ("tint" in $$parsedSource) {
            $$parsedSource["tint"] = $$createField4_0($$parsedSource["tint"]);
        }
        return new ThemePreset(/** @type {Partial<ThemePreset>} */($$parsedSource));
    }
}

/**
 * ThemeSection 对应 manifest 的 theme 段。
 */
export class ThemeSection {
    /**
     * Creates a new ThemeSection instance.
     * @param {Partial<ThemeSection>} [$$source = {}] - The source object to create the ThemeSection.
     */
    constructor($$source = {}) {
        if (!("presets" in $$source)) {
            /**
             * @member
             * @type {ThemePreset[]}
             */
            this["presets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeSection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeSection}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField0_0($$parsedSource["presets"]);
        }
        return new ThemeSection(/** @type {Partial<ThemeSection>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = SourceSection.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = ShaderSection.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ThemeSection.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = ScriptSection.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = ShaderEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = Adapter.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ThemePreset.createFrom;
const $$createType15 = $Create.Array($$createType14);
