// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Stat 是一类出网的累计结果。速率都由「字节/耗时」直接派生，没跑过的类别是 0 而不是猜测值。
 */
export class Stat {
    /**
     * Creates a new Stat instance.
     * @param {Partial<Stat>} [$$source = {}] - The source object to create the Stat.
     */
    constructor($$source = {}) {
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("requests" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requests"] = 0;
        }
        if (!("fails" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fails"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("avg_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_ms"] = 0;
        }
        if (!("max_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_ms"] = 0;
        }
        if (!("avg_bytes_per_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_bytes_per_sec"] = 0;
        }
        if (!("peak_bytes_per_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["peak_bytes_per_sec"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error"] = undefined;
        }
        if (!("last_at_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_at_unix"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stat(/** @type {Partial<Stat>} */($$parsedSource));
    }
}
