// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DoubanHealth 豆瓣数据完整性快照。
 */
export class DoubanHealth {
    /**
     * Creates a new DoubanHealth instance.
     * @param {Partial<DoubanHealth>} [$$source = {}] - The source object to create the DoubanHealth.
     */
    constructor($$source = {}) {
        if (!("total_videos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_videos"] = 0;
        }
        if (!("with_douban_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["with_douban_id"] = 0;
        }
        if (!("missing_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["missing_score"] = 0;
        }
        if (!("missing_subject_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["missing_subject_id"] = 0;
        }
        if (!("on_cooldown" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["on_cooldown"] = 0;
        }
        if (!("duplicate_groups" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicate_groups"] = 0;
        }
        if (!("duplicate_rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicate_rows"] = 0;
        }
        if (!("inherit_candidates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inherit_candidates"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanHealth(/** @type {Partial<DoubanHealth>} */($$parsedSource));
    }
}

/**
 * DoubanInfoRow 豆瓣信息视图（映射到 global_video 的豆瓣相关字段，兼容 updater.go 的调用方式）
 */
export class DoubanInfoRow {
    /**
     * Creates a new DoubanInfoRow instance.
     * @param {Partial<DoubanInfoRow>} [$$source = {}] - The source object to create the DoubanInfoRow.
     */
    constructor($$source = {}) {
        if (!("GlobalID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["GlobalID"] = 0;
        }
        if (!("SubjectID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SubjectID"] = "";
        }
        if (!("Rating" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Rating"] = "";
        }
        if (!("Votes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Votes"] = "";
        }
        if (!("Director" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Director"] = "";
        }
        if (!("Writer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Writer"] = "";
        }
        if (!("Actor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Actor"] = "";
        }
        if (!("Genre" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Genre"] = "";
        }
        if (!("Country" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Country"] = "";
        }
        if (!("Language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Language"] = "";
        }
        if (!("ReleaseDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ReleaseDate"] = "";
        }
        if (!("SeasonCount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SeasonCount"] = "";
        }
        if (!("EpisodeCount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EpisodeCount"] = "";
        }
        if (!("Duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Duration"] = "";
        }
        if (!("Aka" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Aka"] = "";
        }
        if (!("Imdb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Imdb"] = "";
        }
        if (!("PosterURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PosterURL"] = "";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "";
        }
        if (!("VodName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["VodName"] = "";
        }
        if (!("Year" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Year"] = "";
        }
        if (!("VodType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["VodType"] = "";
        }
        if (!("Hotness" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Hotness"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanInfoRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanInfoRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanInfoRow(/** @type {Partial<DoubanInfoRow>} */($$parsedSource));
    }
}

/**
 * FavWithVideo 收藏条目（含视频信息）
 */
export class FavWithVideo {
    /**
     * Creates a new FavWithVideo instance.
     * @param {Partial<FavWithVideo>} [$$source = {}] - The source object to create the FavWithVideo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("vod_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_name"] = "";
        }
        if (!("vod_pic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_pic"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FavWithVideo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FavWithVideo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FavWithVideo(/** @type {Partial<FavWithVideo>} */($$parsedSource));
    }
}

/**
 * GlobalTypeRow 全局类型行
 */
export class GlobalTypeRow {
    /**
     * Creates a new GlobalTypeRow instance.
     * @param {Partial<GlobalTypeRow>} [$$source = {}] - The source object to create the GlobalTypeRow.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Id"] = 0;
        }
        if (!("TypeName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TypeName"] = "";
        }
        if (!("CollectEnabled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["CollectEnabled"] = 0;
        }
        if (!("Sort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Sort"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalTypeRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlobalTypeRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlobalTypeRow(/** @type {Partial<GlobalTypeRow>} */($$parsedSource));
    }
}

/**
 * MergeCandidate 一组疑似同一片的身份。
 */
export class MergeCandidate {
    /**
     * Creates a new MergeCandidate instance.
     * @param {Partial<MergeCandidate>} [$$source = {}] - The source object to create the MergeCandidate.
     */
    constructor($$source = {}) {
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {MergeCandidateRow[]}
             */
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeCandidate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeCandidate}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        return new MergeCandidate(/** @type {Partial<MergeCandidate>} */($$parsedSource));
    }
}

/**
 * MergeCandidateRow 候选组里的一条 global_video。
 */
export class MergeCandidateRow {
    /**
     * Creates a new MergeCandidateRow instance.
     * @param {Partial<MergeCandidateRow>} [$$source = {}] - The source object to create the MergeCandidateRow.
     */
    constructor($$source = {}) {
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("vod_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_name"] = "";
        }
        if (!("year" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["year"] = "";
        }
        if (!("type_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_name"] = "";
        }
        if (!("douban_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["douban_id"] = "";
        }
        if (!("douban_score" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["douban_score"] = "";
        }
        if (!("has_pic" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_pic"] = false;
        }
        if (!("catalog_rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["catalog_rows"] = 0;
        }
        if (!("favorite_rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["favorite_rows"] = 0;
        }
        if (!("history_rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["history_rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeCandidateRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeCandidateRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeCandidateRow(/** @type {Partial<MergeCandidateRow>} */($$parsedSource));
    }
}

/**
 * RecycleItem 是回收站里的一行：被软删除（lifecycle_state='deleted'）的目录条目。
 * 回收站跨源展示，所以每行自带源坐标，不能依赖调用方当前选中的源。
 */
export class RecycleItem {
    /**
     * Creates a new RecycleItem instance.
     * @param {Partial<RecycleItem>} [$$source = {}] - The source object to create the RecycleItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("vod_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_name"] = "";
        }
        if (!("vod_pic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_pic"] = "";
        }
        if (!("vod_year" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_year"] = "";
        }
        if (!("type_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_name"] = "";
        }
        if (!("deleted_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deleted_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecycleItem(/** @type {Partial<RecycleItem>} */($$parsedSource));
    }
}

/**
 * SourceHealth 是单个源的健康度汇总。RecentOnly 让汇总只看最近 N 条，
 * 与历史列表共用同一份"新→旧"的取数口径，避免两处算出不同的成功率。
 */
export class SourceHealth {
    /**
     * Creates a new SourceHealth instance.
     * @param {Partial<SourceHealth>} [$$source = {}] - The source object to create the SourceHealth.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("samples" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["samples"] = 0;
        }
        if (!("oks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["oks"] = 0;
        }
        if (!("success_rate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success_rate"] = 0;
        }
        if (!("avg_latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_latency_ms"] = 0;
        }
        if (!("fail_streak" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fail_streak"] = 0;
        }
        if (!("last_error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_error"] = "";
        }
        if (!("last_error_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_error_unix"] = 0;
        }
        if (!("last_sample_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_sample_unix"] = 0;
        }
        if (!("last_ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["last_ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceHealth(/** @type {Partial<SourceHealth>} */($$parsedSource));
    }
}

/**
 * 源健康度样本。
 * 
 * 采集源是外部站点，接口今天能答明天就可能永久下线。在这之前这类信息只存在于
 * 内存的采集状态和滚动日志里：进程一重启就归零，用户看不到"这个源其实已经连续
 * 失败两周了"，也没法区分偶发抖动和真的失效。这里把每次运行的结果按样本落库，
 * 于是健康度有了历史，失效巡检也有了记账的地方。
 * 
 * 粒度刻意是"一次运行一条"而不是"一页一条"：一次全量采集会上百页，逐页写等于
 * 为了诊断把用户库撑大。运行级样本已经能回答唯一重要的问题——这个源还能不能用。
 */
export class SourceHealthSample {
    /**
     * Creates a new SourceHealthSample instance.
     * @param {Partial<SourceHealthSample>} [$$source = {}] - The source object to create the SourceHealthSample.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency_ms"] = 0;
        }
        if (!("saved" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["saved"] = 0;
        }
        if (!("err" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["err"] = "";
        }
        if (!("ts_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ts_unix"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceHealthSample instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceHealthSample}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceHealthSample(/** @type {Partial<SourceHealthSample>} */($$parsedSource));
    }
}

/**
 * SourceVideoRef identifies a source catalog entry sharing a global identity.
 */
export class SourceVideoRef {
    /**
     * Creates a new SourceVideoRef instance.
     * @param {Partial<SourceVideoRef>} [$$source = {}] - The source object to create the SourceVideoRef.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("vod_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceVideoRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceVideoRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceVideoRef(/** @type {Partial<SourceVideoRef>} */($$parsedSource));
    }
}

export class TableColumn {
    /**
     * Creates a new TableColumn instance.
     * @param {Partial<TableColumn>} [$$source = {}] - The source object to create the TableColumn.
     */
    constructor($$source = {}) {
        if (!("cid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cid"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("col_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["col_type"] = "";
        }
        if (!("notnull" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["notnull"] = 0;
        }
        if (!("dflt_value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dflt_value"] = "";
        }
        if (!("pk" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pk"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableColumn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableColumn}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableColumn(/** @type {Partial<TableColumn>} */($$parsedSource));
    }
}

/**
 * TableStat 单张用户表的行数。
 */
export class TableStat {
    /**
     * Creates a new TableStat instance.
     * @param {Partial<TableStat>} [$$source = {}] - The source object to create the TableStat.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableStat(/** @type {Partial<TableStat>} */($$parsedSource));
    }
}

/**
 * UnionVideo 是合并列表里的一行。SourceKey/SourceVodID 指向代表行，
 * 点进详情或播放就用这一对；Sources 是同一身份还在哪些源里有货。
 */
export class UnionVideo {
    /**
     * Creates a new UnionVideo instance.
     * @param {Partial<UnionVideo>} [$$source = {}] - The source object to create the UnionVideo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("type_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_id"] = "";
        }
        if (!("type_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_name"] = "";
        }
        if (!("vod_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_name"] = "";
        }
        if (!("vod_pic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_pic"] = "";
        }
        if (!("vod_remarks" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_remarks"] = "";
        }
        if (!("vod_year" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_year"] = "";
        }
        if (!("vod_area" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_area"] = "";
        }
        if (!("vod_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_time"] = "";
        }
        if (!("source_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["source_count"] = 0;
        }
        if (!("sources" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnionVideo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnionVideo}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField13_0($$parsedSource["sources"]);
        }
        return new UnionVideo(/** @type {Partial<UnionVideo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = MergeCandidateRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
