// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FavWithVideo {
    /**
     * Creates a new FavWithVideo instance.
     * @param {Partial<FavWithVideo>} [$$source = {}] - The source object to create the FavWithVideo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FavWithVideo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FavWithVideo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FavWithVideo(/** @type {Partial<FavWithVideo>} */($$parsedSource));
    }
}

/**
 * TableColumn 描述某张表的一列
 */
export class TableColumn {
    /**
     * Creates a new TableColumn instance.
     * @param {Partial<TableColumn>} [$$source = {}] - The source object to create the TableColumn.
     */
    constructor($$source = {}) {
        if (!("cid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cid"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("col_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["col_type"] = "";
        }
        if (!("notnull" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["notnull"] = 0;
        }
        if (!("dflt_value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dflt_value"] = "";
        }
        if (!("pk" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pk"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableColumn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableColumn}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableColumn(/** @type {Partial<TableColumn>} */($$parsedSource));
    }
}
