// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * 图片代理限速：避免对同一CDN连续快速请求导致被限流
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as applog$0 from "../applog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as douban$0 from "../douban/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as handler$0 from "../handler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../net/http/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<void>}
 */
export function AddFavorite(req) {
    return $Call.ByID(3060322278, req);
}

/**
 * @param {model$0.Source | null} s
 * @returns {$CancellablePromise<void>}
 */
export function AddSource(s) {
    return $Call.ByID(3305803543, s);
}

/**
 * ApplyWindowSettings 从数据库加载并应用窗口设置（启动时调用）
 * @returns {$CancellablePromise<void>}
 */
export function ApplyWindowSettings() {
    return $Call.ByID(2857942636);
}

/**
 * CancelDownload 取消一个下载任务
 * @param {string} taskId
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelDownload(taskId) {
    return $Call.ByID(1583870197, taskId);
}

/**
 * CheckUpdate 检查是否有新版本（每次调用都获取最新信息，无缓存）
 * @returns {$CancellablePromise<updater$0.UpdateInfo | null>}
 */
export function CheckUpdate() {
    return $Call.ByID(4205003776).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearAllHistory 清空全部观看历史，返回删除的条数
 * @returns {$CancellablePromise<number>}
 */
export function ClearAllHistory() {
    return $Call.ByID(2570218989);
}

/**
 * ClearCache 清除指定类型的缓存
 * @param {$models.ClearCacheReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function ClearCache(req) {
    return $Call.ByID(611049786, req);
}

/**
 * ClearLogs 删除所有日志文件
 * @returns {$CancellablePromise<number>}
 */
export function ClearLogs() {
    return $Call.ByID(1147249795);
}

/**
 * ClearPendingUpdateInfo 清除待处理的更新信息
 * @returns {$CancellablePromise<void>}
 */
export function ClearPendingUpdateInfo() {
    return $Call.ByID(3490463794);
}

/**
 * CompressDetailJSONBrotli and DecompressDetailJSONBrotli are small transport
 * helpers for the browser-side detail cache. The cache lives in localStorage,
 * while Brotli stays in Go so it also works in WebView2 versions that do not
 * expose CompressionStream('br').
 * @param {string} value
 * @returns {$CancellablePromise<string>}
 */
export function CompressDetailJSONBrotli(value) {
    return $Call.ByID(1480694148, value);
}

/**
 * ConfirmShutdown 确认退出：触发应用退出，清理由 ServiceShutdown 统一处理
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmShutdown() {
    return $Call.ByID(1677976559);
}

/**
 * @param {string} encoded
 * @returns {$CancellablePromise<string>}
 */
export function DecompressDetailJSONBrotli(encoded) {
    return $Call.ByID(754899659, encoded);
}

/**
 * DeleteHistoryByVideo 删除某个视频的全部观看历史
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<void>}
 */
export function DeleteHistoryByVideo(req) {
    return $Call.ByID(1131772136, req);
}

/**
 * DeleteHistoryItem 删除单条观看历史
 * @param {$models.HistoryReq} req
 * @returns {$CancellablePromise<void>}
 */
export function DeleteHistoryItem(req) {
    return $Call.ByID(620258675, req);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSource(key) {
    return $Call.ByID(1429877273, key);
}

/**
 * DeleteVideo 删除指定源中的视频（同时清理收藏和历史）
 * @param {handler$0.DeleteVideoReq} req
 * @returns {$CancellablePromise<void>}
 */
export function DeleteVideo(req) {
    return $Call.ByID(1015532375, req);
}

/**
 * DoubanChart 获取豆瓣热榜视频（立即返回，带匹配状态）
 * @returns {$CancellablePromise<douban$0.ChartVideoItem[]>}
 */
export function DoubanChart() {
    return $Call.ByID(3633955378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DoubanChartResolve 用户点击时解析热榜视频（实时检查匹配状态）
 * @param {string} subjectID
 * @returns {$CancellablePromise<douban$0.ChartVideoItem | null>}
 */
export function DoubanChartResolve(subjectID) {
    return $Call.ByID(2696723730, subjectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * DoubanDetail 获取豆瓣详情信息
 * @param {$models.DoubanDetailReq} req
 * @returns {$CancellablePromise<$models.DoubanDetailResp | null>}
 */
export function DoubanDetail(req) {
    return $Call.ByID(2818697375, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * DoubanGetAll 获取全局豆瓣信息表中的记录（支持分页）
 * @param {$models.DoubanGetAllReq} req
 * @returns {$CancellablePromise<$models.DoubanGetAllResp | null>}
 */
export function DoubanGetAll(req) {
    return $Call.ByID(2619093073, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * DoubanSearch 搜索豆瓣获取 subject_id
 * @param {$models.DoubanSearchReq} req
 * @returns {$CancellablePromise<$models.DoubanSearchResp | null>}
 */
export function DoubanSearch(req) {
    return $Call.ByID(2673907054, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * DoubanStatus 返回豆瓣调度器状态
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function DoubanStatus() {
    return $Call.ByID(3246315936).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * DoubanTriggerNow 立即触发一次豆瓣信息补全
 * @returns {$CancellablePromise<number>}
 */
export function DoubanTriggerNow() {
    return $Call.ByID(3510519398);
}

/**
 * DoubanUpdateVideo 手动为某个视频补全豆瓣信息（搜索+解析详情，存入全局表）
 * @param {$models.DoubanUpdateVideoReq} req
 * @returns {$CancellablePromise<douban$0.DoubanInfo | null>}
 */
export function DoubanUpdateVideo(req) {
    return $Call.ByID(409764154, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * DownloadUpdate 下载更新包，通过事件向前端推送进度
 * @param {string} downloadURL
 * @returns {$CancellablePromise<string>}
 */
export function DownloadUpdate(downloadURL) {
    return $Call.ByID(4260299450, downloadURL);
}

/**
 * ExportLogs 按筛选条件把日志写到用户选定的路径。
 * 目标路径由前端 Dialogs.SaveFile 选取，这里只校验扩展名与大小。
 * @param {$models.ExportLogsReq} req
 * @returns {$CancellablePromise<$models.ExportLogsResult | null>}
 */
export function ExportLogs(req) {
    return $Call.ByID(2796678590, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ExportSource 导出某个源的所有数据到 .json.br 文件（Brotli 压缩），返回绝对路径
 * 前端拿到文件路径后可以在系统文件管理器中复制/传给他人
 * @param {string} sourceKey
 * @returns {$CancellablePromise<string>}
 */
export function ExportSource(sourceKey) {
    return $Call.ByID(62555840, sourceKey);
}

/**
 * FileExists 检查文件是否存在（用于前端检查已下载的更新包）
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(path) {
    return $Call.ByID(119183977, path);
}

/**
 * FindSourcesByGlobalId 通过 global_id 查找所有拥有该视频的源
 * @param {number} globalId
 * @returns {$CancellablePromise<db$0.SourceVideoRef[]>}
 */
export function FindSourcesByGlobalId(globalId) {
    return $Call.ByID(3720248185, globalId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<(model$0.Source | null)[]>}
 */
export function GetAllSources() {
    return $Call.ByID(825039058).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetAppVersion 返回当前应用版本号
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(868448036);
}

/**
 * GetCacheInfo 获取缓存信息
 * @returns {$CancellablePromise<$models.CacheInfo | null>}
 */
export function GetCacheInfo() {
    return $Call.ByID(1261043713).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetCloseBehavior 返回关闭行为：true=缩小到托盘，false=直接退出
 * @returns {$CancellablePromise<boolean>}
 */
export function GetCloseBehavior() {
    return $Call.ByID(1172599281);
}

/**
 * GetCollectSchedule 返回采集调度器配置与运行状态
 * @returns {$CancellablePromise<handler$0.SchedulerStatus | null>}
 */
export function GetCollectSchedule() {
    return $Call.ByID(1325905564).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetCollectStatus 返回指定 source 的采集状态
 * @param {string} sourceKey
 * @returns {$CancellablePromise<handler$0.CollectStatus | null>}
 */
export function GetCollectStatus(sourceKey) {
    return $Call.ByID(3019320799, sourceKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * GetDiagnostics 汇总环境、存储、豆瓣、采集调度、源统计与表行数。
 * @returns {$CancellablePromise<$models.Diagnostics | null>}
 */
export function GetDiagnostics() {
    return $Call.ByID(4240521739).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * GetDoubanComments 获取豆瓣评论（带 24h 缓存）
 * @param {$models.DoubanCommentsReq} req
 * @returns {$CancellablePromise<douban$0.DoubanCommentsResp | null>}
 */
export function GetDoubanComments(req) {
    return $Call.ByID(114590814, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetDoubanIntervalMinutes 返回当前生效的豆瓣补全轮询间隔（分钟）。
 * @returns {$CancellablePromise<number>}
 */
export function GetDoubanIntervalMinutes() {
    return $Call.ByID(4089018166);
}

/**
 * GetDownloadDir 返回默认下载目录
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadDir() {
    return $Call.ByID(195395972);
}

/**
 * GetDownloadProgress 查询单个任务状态
 * @param {string} taskId
 * @returns {$CancellablePromise<$models.VideoDownloadStatus | null>}
 */
export function GetDownloadProgress(taskId) {
    return $Call.ByID(3137031638, taskId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<db$0.FavWithVideo[]>}
 */
export function GetFavorites(page, pageSize) {
    return $Call.ByID(338696190, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GetGlobalIdForVideo 获取指定源中某个视频的 global_id
 * @param {string} sourceKey
 * @param {string} vodId
 * @returns {$CancellablePromise<number>}
 */
export function GetGlobalIdForVideo(sourceKey, vodId) {
    return $Call.ByID(2808189905, sourceKey, vodId);
}

/**
 * GetGlobalTypes 获取所有全局类型
 * @returns {$CancellablePromise<(db$0.GlobalTypeRow | null)[]>}
 */
export function GetGlobalTypes() {
    return $Call.ByID(3342542643).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * GetHistoryPosition 返回某集上次播放到的位置（秒），无记录时为 0。
 * @param {$models.HistoryReq} req
 * @returns {$CancellablePromise<number>}
 */
export function GetHistoryPosition(req) {
    return $Call.ByID(1783035000, req);
}

/**
 * GetIgnoredVersion 返回被忽略的版本号
 * @returns {$CancellablePromise<string>}
 */
export function GetIgnoredVersion() {
    return $Call.ByID(2963890851);
}

/**
 * GetLastStartVersion 返回上次启动时的版本号（参考 lx-music-desktop 的 getLastStartInfo）
 * 用于检测版本升级，决定是否展示 changelog
 * @returns {$CancellablePromise<string>}
 */
export function GetLastStartVersion() {
    return $Call.ByID(1781170233);
}

/**
 * GetLogContent 返回指定日志文件的完整内容
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function GetLogContent(filename) {
    return $Call.ByID(1611373010, filename);
}

/**
 * GetLogDir 返回日志所在目录（方便前端在界面上展示"打开日志目录"）
 * @returns {$CancellablePromise<string>}
 */
export function GetLogDir() {
    return $Call.ByID(3962330052);
}

/**
 * GetLogFiles 返回日志文件列表（按日期倒序）及各自大小。
 * @returns {$CancellablePromise<$models.LogFileInfo[]>}
 */
export function GetLogFiles() {
    return $Call.ByID(178353920).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * GetLogKeepDays 返回当前生效的日志保留天数。
 * @returns {$CancellablePromise<number>}
 */
export function GetLogKeepDays() {
    return $Call.ByID(1249745155);
}

/**
 * GetLogLevel 返回当前生效的最低日志级别（DEBUG/INFO/WARN/ERROR）。
 * @returns {$CancellablePromise<string>}
 */
export function GetLogLevel() {
    return $Call.ByID(994171341);
}

/**
 * GetLogList 返回可用日志文件名列表（按时间倒序）
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogList() {
    return $Call.ByID(2452539313).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * GetLogRecords 增量读取内存环形缓冲。sinceSeq 传 0 表示取最近 limit 条。
 * @param {number} sinceSeq
 * @param {number} limit
 * @returns {$CancellablePromise<applog$0.Record[]>}
 */
export function GetLogRecords(sinceSeq, limit) {
    return $Call.ByID(289149917, sinceSeq, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * GetLogStats 返回日志系统的运行状况，供概览卡展示。
 * @returns {$CancellablePromise<$models.LogStats>}
 */
export function GetLogStats() {
    return $Call.ByID(2486763388).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * GetPendingUpdateInfo 返回启动时检测到的待处理更新信息
 * @returns {$CancellablePromise<updater$0.UpdateInfo | null>}
 */
export function GetPendingUpdateInfo() {
    return $Call.ByID(2351689049).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<(handler$0.HistoryItemWithVideo | null)[]>}
 */
export function GetRecentHistory(limit) {
    return $Call.ByID(1166984082, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * @param {$models.RecommendReq} req
 * @returns {$CancellablePromise<(model$0.Video | null)[]>}
 */
export function GetRecommend(req) {
    return $Call.ByID(882431737, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetSetting(key) {
    return $Call.ByID(513391695, key);
}

/**
 * @param {$models.SimilarReq} req
 * @returns {$CancellablePromise<(model$0.Video | null)[]>}
 */
export function GetSimilarVideos(req) {
    return $Call.ByID(45236606, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * GetSourceDetail 返回某个 source_key 的字段定义和示例数据
 * @param {string} sourceKey
 * @returns {$CancellablePromise<handler$0.SourceDetail | null>}
 */
export function GetSourceDetail(sourceKey) {
    return $Call.ByID(2597841381, sourceKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType51($result);
    }));
}

/**
 * GetSourceParamsDoc 返回采集接口参数规范，供前端展示规则指南
 * @param {string} sourceKey
 * @returns {$CancellablePromise<handler$0.SourceParamsDoc | null>}
 */
export function GetSourceParamsDoc(sourceKey) {
    return $Call.ByID(1529784668, sourceKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * @returns {$CancellablePromise<model$0.SourceStat[]>}
 */
export function GetSourceStats() {
    return $Call.ByID(3049570047).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * @param {handler$0.GetTypesReq} req
 * @returns {$CancellablePromise<(model$0.VType | null)[]>}
 */
export function GetTypes(req) {
    return $Call.ByID(757410166, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType58($result);
    }));
}

/**
 * @param {handler$0.VideoDetailReq} req
 * @returns {$CancellablePromise<handler$0.VideoDetailResp | null>}
 */
export function GetVideoDetail(req) {
    return $Call.ByID(2872254585, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType60($result);
    }));
}

/**
 * @param {handler$0.VideoListReq} req
 * @returns {$CancellablePromise<handler$0.VideoListResp | null>}
 */
export function GetVideoList(req) {
    return $Call.ByID(2333127456, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType62($result);
    }));
}

/**
 * GetWatchedEpisodes 返回指定视频已观看的所有集数
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<number[]>}
 */
export function GetWatchedEpisodes(req) {
    return $Call.ByID(1791408515, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * GetYearsAndAreas 返回当前源下所有可选的年份/地区，供前端筛选下拉框使用
 * @param {string} sourceKey
 * @returns {$CancellablePromise<handler$0.YearsResp | null>}
 */
export function GetYearsAndAreas(sourceKey) {
    return $Call.ByID(3741290708, sourceKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType65($result);
    }));
}

/**
 * GracefulShutdown 优雅关闭：等待所有采集任务完成当前页后退出
 * @returns {$CancellablePromise<void>}
 */
export function GracefulShutdown() {
    return $Call.ByID(1331657626);
}

/**
 * IgnoreVersion 忽略指定版本（存入数据库，下次不再提示）
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function IgnoreVersion(version) {
    return $Call.ByID(4170636743, version);
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function ImportSource(filePath) {
    return $Call.ByID(482654387, filePath);
}

/**
 * ImportSourceFromBase64 imports source data provided by the browser.
 * @param {string} filename
 * @param {string} b64Content
 * @returns {$CancellablePromise<string>}
 */
export function ImportSourceFromBase64(filename, b64Content) {
    return $Call.ByID(1908490216, filename, b64Content);
}

/**
 * ImportSourceVideos 将用户挑选的源站搜索视频入库（压缩字段 + 合并写入）
 * sourceKey 用于确定入库的目标源表；videos 中携带的豆瓣信息也会写入全局 douban_info 表
 * 返回成功入库的条数
 * @param {string} sourceKey
 * @param {(model$0.Video | null)[]} videos
 * @returns {$CancellablePromise<number>}
 */
export function ImportSourceVideos(sourceKey, videos) {
    return $Call.ByID(685252647, sourceKey, videos);
}

/**
 * InstallUpdate 安装更新并退出当前程序
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate(filePath) {
    return $Call.ByID(1255131359, filePath);
}

/**
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFavorite(req) {
    return $Call.ByID(2560518651, req);
}

/**
 * IsSchedulerRunning 检查是否有调度任务正在运行（采集调度或豆瓣调度）
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSchedulerRunning() {
    return $Call.ByID(198896967);
}

/**
 * ListDownloads 返回所有任务快照
 * @returns {$CancellablePromise<$models.VideoDownloadStatus[]>}
 */
export function ListDownloads() {
    return $Call.ByID(1588133360).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType66($result);
    }));
}

/**
 * OpenFileInExplorer 在系统文件管理器中打开该文件（定位到文件）
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function OpenFileInExplorer(path) {
    return $Call.ByID(2357579489, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function OpenFolder(path) {
    return $Call.ByID(1764278455, path);
}

/**
 * PauseCollect 暂停指定 source_key 的采集
 * @param {handler$0.CollectReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function PauseCollect(req) {
    return $Call.ByID(2619798971, req);
}

/**
 * PauseDownload 暂停一个下载任务
 * @param {string} taskId
 * @returns {$CancellablePromise<boolean>}
 */
export function PauseDownload(taskId) {
    return $Call.ByID(4060580411, taskId);
}

/**
 * ProbeSources 逐个探测采集源接口能否应答：带 ac=videolist&pg=1 发一次 GET，
 * 记录状态码与首包耗时。只读前 4KB 用于判断返回的是不是列表结构，
 * 不把整个响应灌进内存，也不落库。
 * @returns {$CancellablePromise<$models.SourceProbe[]>}
 */
export function ProbeSources() {
    return $Call.ByID(1486404871).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType68($result);
    }));
}

/**
 * ProxyImage proxies a remote image through the constrained proxy service.
 * @param {string} urlStr
 * @returns {$CancellablePromise<string>}
 */
export function ProxyImage(urlStr) {
    return $Call.ByID(263031934, urlStr);
}

/**
 * ReadLogPage 从指定日志文件按行读取一页结构化记录，支持级别过滤与关键词检索。
 * 逐行流式扫描，内存占用与页大小相关而与文件大小无关。
 * @param {$models.LogPageReq} req
 * @returns {$CancellablePromise<$models.LogPageResp | null>}
 */
export function ReadLogPage(req) {
    return $Call.ByID(951167816, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType70($result);
    }));
}

/**
 * RemoveDownload 从列表移除任务记录（不会删除已下载文件）
 * @param {string} taskId
 * @returns {$CancellablePromise<boolean>}
 */
export function RemoveDownload(taskId) {
    return $Call.ByID(755249543, taskId);
}

/**
 * @param {$models.FavReq} req
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFavorite(req) {
    return $Call.ByID(2813482587, req);
}

/**
 * RestartApp 重启应用
 * @returns {$CancellablePromise<void>}
 */
export function RestartApp() {
    return $Call.ByID(2288315693);
}

/**
 * ResumeCollect 恢复指定 source_key 的采集
 * @param {handler$0.CollectReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function ResumeCollect(req) {
    return $Call.ByID(3649818006, req);
}

/**
 * ResumeDownload 恢复一个暂停的下载任务
 * @param {string} taskId
 * @returns {$CancellablePromise<boolean>}
 */
export function ResumeDownload(taskId) {
    return $Call.ByID(1050334332, taskId);
}

/**
 * RunSourceAction 统一执行数据源管理操作
 * action:
 *   - truncate       // 仅清空该源的视频/剧集/分类数据（保留 source 元信息）
 *   - recreate       // 删除并重建该源的三张表（数据全部丢失）
 *   - delete_source  // 删除该源的所有表 + sources 记录
 *   - delete_video   // 删除单条 vod_id（同时清理剧集）
 * @param {$models.SourceActionReq} req
 * @returns {$CancellablePromise<string>}
 */
export function RunSourceAction(req) {
    return $Call.ByID(3557857863, req);
}

/**
 * SaveLastStartVersion 保存当前版本号（启动时调用）
 * @returns {$CancellablePromise<void>}
 */
export function SaveLastStartVersion() {
    return $Call.ByID(3003538738);
}

/**
 * @param {$models.HistoryReq} req
 * @returns {$CancellablePromise<void>}
 */
export function SaveWatchHistory(req) {
    return $Call.ByID(1875736803, req);
}

/**
 * SearchSource 用 wd=keyword 去指定源站搜索指定页，返回富字段结果（不入库）
 * page=1 开始；pageSize<=0 时使用源的默认条数
 * 入库请调用 ImportSourceVideos
 * @param {string} sourceKey
 * @param {string} keyword
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<handler$0.SearchSourceResult | null>}
 */
export function SearchSource(sourceKey, keyword, page, pageSize) {
    return $Call.ByID(3664031674, sourceKey, keyword, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType72($result);
    }));
}

/**
 * @param {handler$0.VideoSearchReq} req
 * @returns {$CancellablePromise<handler$0.VideoListResp | null>}
 */
export function SearchVideos(req) {
    return $Call.ByID(4044799011, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType62($result);
    }));
}

/**
 * ServeHLSProxy handles the same-origin HLS endpoint registered in main.go.
 * @param {http$0.ResponseWriter} w
 * @param {http$0.Request | null} r
 * @returns {$CancellablePromise<void>}
 */
export function ServeHLSProxy(w, r) {
    return $Call.ByID(1232509205, w, r);
}

/**
 * SetCloseBehavior 设置关闭行为并持久化
 * @param {boolean} minimize
 * @returns {$CancellablePromise<void>}
 */
export function SetCloseBehavior(minimize) {
    return $Call.ByID(1467815861, minimize);
}

/**
 * SetCollectSchedule 修改采集调度配置（持久化到 settings）
 * @param {handler$0.CollectScheduleConfig} cfg
 * @returns {$CancellablePromise<handler$0.CollectScheduleConfig>}
 */
export function SetCollectSchedule(cfg) {
    return $Call.ByID(2657596784, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType73($result);
    }));
}

/**
 * SetDoubanIntervalMinutes 立刻改豆瓣轮询间隔并持久化，返回真正生效的分钟数。
 * 下限 1 分钟：豆瓣的反爬只认「够慢」，这里不给更小的值兜底空间。
 * @param {number} minutes
 * @returns {$CancellablePromise<number>}
 */
export function SetDoubanIntervalMinutes(minutes) {
    return $Call.ByID(1304670314, minutes);
}

/**
 * SetDownloadDir 设置自定义下载目录（空字符串则重置为默认）
 * @param {string} dir
 * @returns {$CancellablePromise<string>}
 */
export function SetDownloadDir(dir) {
    return $Call.ByID(1517353144, dir);
}

/**
 * SetGlobalTypeCollectEnabled 设置全局类型的采集开关
 * @param {$models.SetGlobalTypeCollectEnabledReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function SetGlobalTypeCollectEnabled(req) {
    return $Call.ByID(3985382065, req);
}

/**
 * SetLogKeepDays 改日志保留天数，立刻按新值清理一次并持久化。
 * @param {number} days
 * @returns {$CancellablePromise<number>}
 */
export function SetLogKeepDays(days) {
    return $Call.ByID(573212871, days);
}

/**
 * SetLogLevel 运行时切换日志级别并持久化，立即生效、无需重启。
 * @param {string} level
 * @returns {$CancellablePromise<string>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(1320081097, level);
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(4080419067, key, value);
}

/**
 * SetSourceSchedule 设置单个源的调度配置
 * @param {handler$0.SourceScheduleReq} req
 * @returns {$CancellablePromise<void>}
 */
export function SetSourceSchedule(req) {
    return $Call.ByID(318442965, req);
}

/**
 * SetTitleBarTheme 切换标题栏主题（"dark" 或 "light"）
 * Wails 在启动时已设置 CustomTheme；这里通过 ExecJS 让系统重新应用。
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTitleBarTheme(theme) {
    return $Call.ByID(3526124207, theme);
}

/**
 * @param {handler$0.CollectReq} req
 * @returns {$CancellablePromise<handler$0.CollectStatus | null>}
 */
export function StartCollect(req) {
    return $Call.ByID(3723794385, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * StartLogStream 把新产生的日志以 app:log 事件推送给前端。多次调用共享一个转发协程。
 * @returns {$CancellablePromise<boolean>}
 */
export function StartLogStream() {
    return $Call.ByID(2003392841);
}

/**
 * @param {$models.VideoDownloadReq} req
 * @returns {$CancellablePromise<$models.VideoDownloadStatus | null>}
 */
export function StartVideoDownload(req) {
    return $Call.ByID(565771572, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * StopBackgroundCollect 停止后台循环采集，并等待短时间让状态同步
 * @returns {$CancellablePromise<boolean>}
 */
export function StopBackgroundCollect() {
    return $Call.ByID(3253186999);
}

/**
 * StopCollect 停止指定 source_key 的采集
 * @param {handler$0.CollectReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function StopCollect(req) {
    return $Call.ByID(3613972355, req);
}

/**
 * StopLogStream 释放一次订阅；最后一个调用方退出时才真正停止转发。
 * @returns {$CancellablePromise<boolean>}
 */
export function StopLogStream() {
    return $Call.ByID(87049575);
}

/**
 * SyncGlobalTypes 从所有源同步类型到全局类型表
 * @returns {$CancellablePromise<number>}
 */
export function SyncGlobalTypes() {
    return $Call.ByID(1357429276);
}

/**
 * @param {$models.TriggerCollectReq} req
 * @returns {$CancellablePromise<boolean>}
 */
export function TriggerCollectNow(req) {
    return $Call.ByID(2169977407, req);
}

/**
 * @param {model$0.Source | null} s
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSource(s) {
    return $Call.ByID(503911923, s);
}

/**
 * WindowGetResizable 返回窗口是否可调整大小
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowGetResizable() {
    return $Call.ByID(1416981238);
}

/**
 * WindowGetSize 返回当前窗口尺寸
 * @returns {$CancellablePromise<$models.WindowSizeResp | null>}
 */
export function WindowGetSize() {
    return $Call.ByID(4147060312).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType75($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowIsFs() {
    return $Call.ByID(1008355380);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowIsMax() {
    return $Call.ByID(3066008507);
}

/**
 * WindowSetFullscreen 切换"系统级全屏"（覆盖任务栏，移除窗口边框）
 * 
 * 	enter=true  → 进入全屏
 * 	enter=false → 退出全屏
 * 
 * Wails 的 WindowFullscreen 在 Windows 上会自动移除标题栏并覆盖任务栏。
 * @param {boolean} enter
 * @returns {$CancellablePromise<void>}
 */
export function WindowSetFullscreen(enter) {
    return $Call.ByID(851183688, enter);
}

/**
 * WindowSetResizable 设置窗口是否可拖动调整大小
 * @param {boolean} resizable
 * @returns {$CancellablePromise<void>}
 */
export function WindowSetResizable(resizable) {
    return $Call.ByID(1000028290, resizable);
}

/**
 * WindowSetSize 设置窗口尺寸
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function WindowSetSize(width, height) {
    return $Call.ByID(2534129132, width, height);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function WindowToggleMax() {
    return $Call.ByID(1159040971);
}

/**
 * WriteLog 写入一条日志；同时记录到文件（按天滚动）并进入内存时间线
 * @param {$models.LogEntry} entry
 * @returns {$CancellablePromise<boolean>}
 */
export function WriteLog(entry) {
    return $Call.ByID(1233255992, entry);
}

// Private type creation functions
const $$createType0 = updater$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = douban$0.ChartVideoItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Nullable($$createType2);
const $$createType5 = $models.DoubanDetailResp.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.DoubanGetAllResp.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.DoubanSearchResp.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = douban$0.DoubanInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.ExportLogsResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = db$0.SourceVideoRef.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = model$0.Source.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.CacheInfo.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = handler$0.SchedulerStatus.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = handler$0.CollectStatus.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = $models.Diagnostics.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = douban$0.DoubanCommentsResp.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = $models.VideoDownloadStatus.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = db$0.FavWithVideo.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = db$0.GlobalTypeRow.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = $models.LogFileInfo.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = $Create.Array($Create.Any);
const $$createType41 = applog$0.Record.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = $models.LogStats.createFrom;
const $$createType44 = handler$0.HistoryItemWithVideo.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = $Create.Array($$createType45);
const $$createType47 = model$0.Video.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = handler$0.SourceDetail.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = handler$0.SourceParamsDoc.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
const $$createType54 = model$0.SourceStat.createFrom;
const $$createType55 = $Create.Array($$createType54);
const $$createType56 = model$0.VType.createFrom;
const $$createType57 = $Create.Nullable($$createType56);
const $$createType58 = $Create.Array($$createType57);
const $$createType59 = handler$0.VideoDetailResp.createFrom;
const $$createType60 = $Create.Nullable($$createType59);
const $$createType61 = handler$0.VideoListResp.createFrom;
const $$createType62 = $Create.Nullable($$createType61);
const $$createType63 = $Create.Array($Create.Any);
const $$createType64 = handler$0.YearsResp.createFrom;
const $$createType65 = $Create.Nullable($$createType64);
const $$createType66 = $Create.Array($$createType31);
const $$createType67 = $models.SourceProbe.createFrom;
const $$createType68 = $Create.Array($$createType67);
const $$createType69 = $models.LogPageResp.createFrom;
const $$createType70 = $Create.Nullable($$createType69);
const $$createType71 = handler$0.SearchSourceResult.createFrom;
const $$createType72 = $Create.Nullable($$createType71);
const $$createType73 = handler$0.CollectScheduleConfig.createFrom;
const $$createType74 = $models.WindowSizeResp.createFrom;
const $$createType75 = $Create.Nullable($$createType74);
