// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateInfo 更新信息（返回给前端）
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("has_update" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_update"] = false;
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (!("release_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_name"] = "";
        }
        if (!("release_notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_notes"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("asset_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["asset_name"] = "";
        }
        if (!("asset_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["asset_size"] = 0;
        }
        if (!("published_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["published_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}
