// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * A MIMEHeader represents a MIME-style header mapping
 * keys to sets of values.
 * @typedef {$models.MIMEHeader} MIMEHeader
 */
