package updater

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseReleaseAsset(t *testing.T) {
	cases := []struct {
		name      string
		url       string
		wantOwner string
		wantRepo  string
		wantTag   string
		wantFile  string
		wantOK    bool
	}{
		{
			name: "direct", url: "https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/cczjVideo-windows-amd64-2.2.1.exe",
			wantOwner: "ws-cczj", wantRepo: "CCZJ-Video", wantTag: "v2.2.1",
			wantFile: "cczjVideo-windows-amd64-2.2.1.exe", wantOK: true,
		},
		{
			name: "through a proxy prefix", url: "https://gh-proxy.org/https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/a.zip",
			wantOwner: "ws-cczj", wantRepo: "CCZJ-Video", wantTag: "v2.2.1", wantFile: "a.zip", wantOK: true,
		},
		{
			name: "objects host is not a release asset", url: "https://objects.githubusercontent.com/foo/bar",
			wantOK: false,
		},
		{
			name: "missing file segment", url: "https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1",
			wantOK: false,
		},
		{
			name: "raw file url", url: "https://raw.githubusercontent.com/ws-cczj/CCZJ-Video/main/version.json",
			wantOK: false,
		},
		{
			name: "empty", url: "", wantOK: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			owner, repo, tag, file, ok := parseReleaseAsset(tc.url)
			if ok != tc.wantOK {
				t.Fatalf("ok = %v, want %v", ok, tc.wantOK)
			}
			if !ok {
				return
			}
			if owner != tc.wantOwner || repo != tc.wantRepo || tag != tc.wantTag || file != tc.wantFile {
				t.Fatalf("parsed %q %q %q %q", owner, repo, tag, file)
			}
		})
	}
}

func TestParseChecksums(t *testing.T) {
	const (
		lower  = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
		upper  = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
		single = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
	)
	body := []byte(strings.Join([]string{
		"# generated by build/windows/package.ps1",
		"",
		lower + "  cczjVideo-windows-amd64-2.2.1.exe",
		// 大写摘要 + "./" 前缀：都要归一，否则清单大小写或写法一变就匹配不上。
		upper + "  ./App.zip",
		// 单个空格分隔（非 coreutils 规范写法）也接受：解析宽容，比对严格。
		single + " third.txt",
		"tooshort  bad.exe",
		"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz bad2.exe",
		lower,
	}, "\r\n"))

	got := parseChecksums(body)

	want := map[string]string{
		"cczjvideo-windows-amd64-2.2.1.exe": lower,
		"app.zip":                           strings.ToLower(upper),
		"third.txt":                         single,
	}
	if len(got) != len(want) {
		t.Fatalf("expected %d entries, got %d: %v", len(want), len(got), got)
	}
	for name, digest := range want {
		if got[name] != digest {
			t.Errorf("%s = %q, want %q", name, got[name], digest)
		}
	}
}

func TestFetchReleaseChecksumsRejectsForeignRepoBeforeAnyRequest(t *testing.T) {
	// 校验清单必须来自本应用仓库；否则会拿别人发布的哈希来给产物背书。
	if _, err := fetchReleaseChecksums("evil", "CCZJ-Video", "v1.0.0"); err == nil {
		t.Fatal("expected foreign owner to be rejected")
	}
	if _, err := fetchReleaseChecksums(repoOwner, "other-repo", "v1.0.0"); err == nil {
		t.Fatal("expected foreign repo to be rejected")
	}
}

func TestRequireArtifactRejectsNonReleaseURL(t *testing.T) {
	// 下载源必须是 GitHub Release 资源，否则连该取哪个 tag 的清单都不知道。
	for _, u := range []string{"", "https://example.com/a.exe", "not a url"} {
		if _, err := requireArtifact(u); err == nil {
			t.Fatalf("expected %q to be rejected", u)
		}
	}
}

func TestUpdateStagingNameKeepsExtension(t *testing.T) {
	// 扩展名写死成 .exe 会让 InstallUpdate 按 exe 分支热替换，把 zip 字节盖进应用本体。
	cases := map[string]string{
		"https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/app.EXE":   stagingPrefix + ".exe",
		"https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/app.zip":   stagingPrefix + ".zip",
		"https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/setup.msi": stagingPrefix + ".msi",
		// 认不出的扩展名一律 .bin：InstallUpdate 只会走"打开目录"分支，不会执行它。
		"https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/app.tar.gz": stagingPrefix + ".gz",
		"https://example.com/whatever":                                              stagingPrefix + ".bin",
		"":                                                                          stagingPrefix + ".bin",
	}
	for url, want := range cases {
		if got := updateStagingName(url); got != want {
			t.Errorf("updateStagingName(%q) = %q, want %q", url, got, want)
		}
	}
}

func TestIsUpdateArtifact(t *testing.T) {
	appDir := getAppDir()
	exeName := getAppExeName()
	if appDir == "." || exeName == "" {
		t.Skip("cannot resolve the running executable in this environment")
	}
	exeBase := strings.TrimSuffix(exeName, filepath.Ext(exeName))

	cases := []struct {
		name string
		path string
		want bool
	}{
		{"staged exe", filepath.Join(appDir, stagingPrefix+".exe"), true},
		{"staged zip", filepath.Join(appDir, stagingPrefix+".zip"), true},
		{"staged bin", filepath.Join(appDir, stagingPrefix+".bin"), true},
		{"legacy underscore pattern", filepath.Join(appDir, exeBase+"_update.exe"), true},
		{"legacy numbered pattern", filepath.Join(appDir, exeBase+"_update(2).exe"), true},
		// 这个是攻击面：InstallUpdate 会 exec 传进来的路径。
		{"the running app itself", filepath.Join(appDir, exeName), false},
		{"unrelated file in app dir", filepath.Join(appDir, "calc.exe"), false},
		{"nested staged name", filepath.Join(appDir, "sub", stagingPrefix+".exe"), false},
		{"parent dir staged name", filepath.Join(appDir, "..", stagingPrefix+".exe"), false},
		{"absolute path outside", filepath.Join(filepath.VolumeName(appDir)+string(filepath.Separator), stagingPrefix+".exe"), false},
		{"empty", "", false},
		{"whitespace", "   ", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := isUpdateArtifact(tc.path); got != tc.want {
				t.Fatalf("isUpdateArtifact(%q) = %v, want %v", tc.path, got, tc.want)
			}
		})
	}
}

func TestVerifyArtifact(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "payload.bin")
	content := []byte("cczj video update payload")
	if err := os.WriteFile(path, content, 0644); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(content)
	good := hex.EncodeToString(sum[:])

	if err := verifyArtifact(path, good); err != nil {
		t.Fatalf("expected match, got %v", err)
	}
	// 大小写不敏感：清单里的摘要可能写成大写。
	if err := verifyArtifact(path, strings.ToUpper(good)); err != nil {
		t.Fatalf("expected case-insensitive match, got %v", err)
	}
	if err := verifyArtifact(path, strings.Repeat("0", 64)); err == nil {
		t.Fatal("expected mismatch to fail")
	}
	// 没有期望摘要时必须失败，不能"跳过校验"当成通过。
	if err := verifyArtifact(path, ""); err == nil {
		t.Fatal("expected empty expectation to fail")
	}
	if err := verifyArtifact(filepath.Join(dir, "missing.bin"), good); err == nil {
		t.Fatal("expected missing file to fail")
	}
}

func TestScanAlreadyDownloadedFindsStagedArtifact(t *testing.T) {
	dir := t.TempDir()
	// scanAlreadyDownloaded 只看真实应用目录，这里只验证命名规则与 glob 一致。
	staged := filepath.Join(dir, updateStagingName("https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/app.zip"))
	if err := os.WriteFile(staged, []byte(strings.Repeat("x", 2048)), 0644); err != nil {
		t.Fatal(err)
	}
	matches, err := filepath.Glob(filepath.Join(dir, stagingPrefix+".*"))
	if err != nil || len(matches) != 1 {
		t.Fatalf("staged artifact is not discoverable by the scan pattern: %v %v", matches, err)
	}
	if matches[0] != staged {
		t.Fatalf("glob matched %v, want %v", matches[0], staged)
	}
}
