package updater

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseReleaseAsset(t *testing.T) {
	cases := []struct {
		name      string
		url       string
		wantOwner string
		wantRepo  string
		wantTag   string
		wantFile  string
		wantOK    bool
	}{
		{
			name: "direct", url: "https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/cczjVideo-windows-amd64-2.2.1.exe",
			wantOwner: "ws-cczj", wantRepo: "CCZJ-Video", wantTag: "v2.2.1",
			wantFile: "cczjVideo-windows-amd64-2.2.1.exe", wantOK: true,
		},
		{
			name: "through a proxy prefix", url: "https://gh-proxy.org/https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/a.zip",
			wantOwner: "ws-cczj", wantRepo: "CCZJ-Video", wantTag: "v2.2.1", wantFile: "a.zip", wantOK: true,
		},
		{
			name: "objects host is not a release asset", url: "https://objects.githubusercontent.com/foo/bar",
			wantOK: false,
		},
		{
			name: "missing file segment", url: "https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1",
			wantOK: false,
		},
		{
			name: "raw file url", url: "https://raw.githubusercontent.com/ws-cczj/CCZJ-Video/main/version.json",
			wantOK: false,
		},
		{
			name: "empty", url: "", wantOK: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			owner, repo, tag, file, ok := parseReleaseAsset(tc.url)
			if ok != tc.wantOK {
				t.Fatalf("ok = %v, want %v", ok, tc.wantOK)
			}
			if !ok {
				return
			}
			if owner != tc.wantOwner || repo != tc.wantRepo || tag != tc.wantTag || file != tc.wantFile {
				t.Fatalf("parsed %q %q %q %q", owner, repo, tag, file)
			}
		})
	}
}

func TestParseChecksums(t *testing.T) {
	const (
		lower  = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
		upper  = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
		single = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
	)
	body := []byte(strings.Join([]string{
		"# generated by build/windows/package.ps1",
		"",
		lower + "  cczjVideo-windows-amd64-2.2.1.exe",
		// 大写摘要 + "./" 前缀：都要归一，否则清单大小写或写法一变就匹配不上。
		upper + "  ./App.zip",
		// 单个空格分隔（非 coreutils 规范写法）也接受：解析宽容，比对严格。
		single + " third.txt",
		"tooshort  bad.exe",
		"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz bad2.exe",
		lower,
	}, "\r\n"))

	got := parseChecksums(body)

	want := map[string]string{
		"cczjvideo-windows-amd64-2.2.1.exe": lower,
		"app.zip":                           strings.ToLower(upper),
		"third.txt":                         single,
	}
	if len(got) != len(want) {
		t.Fatalf("expected %d entries, got %d: %v", len(want), len(got), got)
	}
	for name, digest := range want {
		if got[name] != digest {
			t.Errorf("%s = %q, want %q", name, got[name], digest)
		}
	}
}

func TestFetchReleaseChecksumsRejectsForeignRepoBeforeAnyRequest(t *testing.T) {
	// 校验清单必须来自本应用仓库；否则会拿别人发布的哈希来给产物背书。
	if _, err := fetchReleaseChecksums("evil", "CCZJ-Video", "v1.0.0"); err == nil {
		t.Fatal("expected foreign owner to be rejected")
	}
	if _, err := fetchReleaseChecksums(repoOwner, "other-repo", "v1.0.0"); err == nil {
		t.Fatal("expected foreign repo to be rejected")
	}
}

func TestRequireArtifactRejectsNonReleaseURL(t *testing.T) {
	// 下载源必须是 GitHub Release 资源，否则连该取哪个 tag 的清单都不知道。
	for _, u := range []string{"", "https://example.com/a.exe", "not a url"} {
		if _, err := requireArtifact(u); err == nil {
			t.Fatalf("expected %q to be rejected", u)
		}
	}
}

func hexDigest(c byte) string { return strings.Repeat(string(c), sha256.Size*2) }

func voteSums(t *testing.T, body string) map[string]string {
	t.Helper()
	sums := parseChecksums([]byte(body))
	if len(sums) == 0 {
		t.Fatal("fixture checksums did not parse")
	}
	return sums
}

// 清单是整条更新链上唯一不可信的取回动作：它只能走 github.com 直连的话，
// 大陆网络上的用户会在下载第一步就被挡住，而产物本身明明能从加速站顺利下完。
func TestDecideChecksumsPrefersDirect(t *testing.T) {
	direct := voteSums(t, hexDigest('a')+"  app.exe")
	proxy := voteSums(t, hexDigest('b')+"  app.exe")
	votes := []checksumVote{{party: "gh-proxy.com", sums: proxy}}

	got, party, err := decideChecksums(direct, nil, votes)
	if err != nil {
		t.Fatal(err)
	}
	if party != "github.com" {
		t.Fatalf("party = %q, want the direct channel to win outright", party)
	}
	if got["app.exe"] != hexDigest('a') {
		t.Fatalf("direct manifest was not used: %v", got)
	}
}

func TestDecideChecksumsNeedsTwoIndependentOperators(t *testing.T) {
	good := voteSums(t, hexDigest('a')+"  app.exe")
	failing := errors.New("dial tcp: lookup github.com: no such host")

	// v4/v6 与主站是同一家：三条回答完全一致，也凑不出第二票。
	sameFamily := []checksumVote{
		{party: "gh-proxy.org", sums: good},
		{party: "gh-proxy.org", sums: good},
		{party: "gh-proxy.org", sums: good},
	}
	if _, _, err := decideChecksums(nil, failing, sameFamily); err == nil {
		t.Fatal("一家运营商自问自答不该被当成两处一致")
	}

	twoParties := []checksumVote{
		{party: "gh-proxy.org", sums: good},
		{party: "gh-proxy.com", sums: good},
	}
	got, party, err := decideChecksums(nil, failing, twoParties)
	if err != nil {
		t.Fatalf("two agreeing operators should be accepted: %v", err)
	}
	if got["app.exe"] != hexDigest('a') {
		t.Fatalf("wrong manifest adopted: %v", got)
	}
	if !strings.Contains(party, "gh-proxy.org") || !strings.Contains(party, "gh-proxy.com") {
		t.Fatalf("party = %q, want both operators named for the log", party)
	}
}

func TestDecideChecksumsRejectsDisagreementAndSelfContradiction(t *testing.T) {
	failing := errors.New("直连超时")
	left := voteSums(t, hexDigest('a')+"  app.exe")
	right := voteSums(t, hexDigest('b')+"  app.exe")

	// 两家一致才有票：各说各话时谁都不能单独决定给用户装什么字节。
	if _, _, err := decideChecksums(nil, failing, []checksumVote{
		{party: "gh-proxy.org", sums: left},
		{party: "gh-proxy.com", sums: right},
	}); err == nil {
		t.Fatal("两份不一致的清单不该被采信")
	}

	// 同一家先后给出不一致的清单，这家整体作废：少了它，剩下只有一家的票，
	// 凑不出第二处一致。它不作废的话，这组票本来能靠它和 gh-proxy.com 的一致通过。
	if _, _, err := decideChecksums(nil, failing, []checksumVote{
		{party: "gh-proxy.org", sums: left},
		{party: "gh-proxy.org", sums: right},
		{party: "gh-proxy.com", sums: left},
	}); err == nil {
		t.Fatal("内部自相矛盾的运营商不该有票")
	}

	// 一家都没回答时，错误里要留得下直连的原因，否则排查只能猜。
	_, _, err := decideChecksums(nil, failing, []checksumVote{
		{party: "gh-proxy.org", err: errors.New("HTTP 502")},
	})
	if err == nil || !strings.Contains(err.Error(), "直连超时") {
		t.Fatalf("error should carry the direct failure, got %v", err)
	}
}

func TestChecksumChannelsGroupProxiesByOperator(t *testing.T) {
	channels := checksumChannels()
	if channels[0].prefix != "" {
		t.Fatal("第一个通道必须是直连：它优先，也是唯一由我们自己发布内容的通道")
	}
	parties := map[string]int{}
	for _, ch := range channels {
		if ch.party == "" {
			t.Fatalf("channel %q has no operator", ch.prefix)
		}
		parties[ch.party]++
	}
	if len(parties) < requiredParties {
		t.Fatalf("only %d distinct operators: quorum of %d is unreachable", len(parties), requiredParties)
	}
}

func TestUpdateStagingNameKeepsExtension(t *testing.T) {
	// 扩展名写死成 .exe 会让 InstallUpdate 按 exe 分支热替换，把 zip 字节盖进应用本体。
	cases := map[string]string{
		"https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/app.EXE":   stagingPrefix + ".exe",
		"https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/app.zip":   stagingPrefix + ".zip",
		"https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/setup.msi": stagingPrefix + ".msi",
		// 认不出的扩展名一律 .bin：InstallUpdate 只会走"打开目录"分支，不会执行它。
		"https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/app.tar.gz": stagingPrefix + ".gz",
		"https://example.com/whatever":                                              stagingPrefix + ".bin",
		"":                                                                          stagingPrefix + ".bin",
	}
	for url, want := range cases {
		if got := updateStagingName(url); got != want {
			t.Errorf("updateStagingName(%q) = %q, want %q", url, got, want)
		}
	}
}

func TestIsUpdateArtifact(t *testing.T) {
	appDir := getAppDir()
	exeName := getAppExeName()
	if appDir == "." || exeName == "" {
		t.Skip("cannot resolve the running executable in this environment")
	}
	exeBase := strings.TrimSuffix(exeName, filepath.Ext(exeName))

	cases := []struct {
		name string
		path string
		want bool
	}{
		{"staged exe", filepath.Join(appDir, stagingPrefix+".exe"), true},
		{"staged zip", filepath.Join(appDir, stagingPrefix+".zip"), true},
		{"staged bin", filepath.Join(appDir, stagingPrefix+".bin"), true},
		{"legacy underscore pattern", filepath.Join(appDir, exeBase+"_update.exe"), true},
		{"legacy numbered pattern", filepath.Join(appDir, exeBase+"_update(2).exe"), true},
		// 这个是攻击面：InstallUpdate 会 exec 传进来的路径。
		{"the running app itself", filepath.Join(appDir, exeName), false},
		{"unrelated file in app dir", filepath.Join(appDir, "calc.exe"), false},
		{"nested staged name", filepath.Join(appDir, "sub", stagingPrefix+".exe"), false},
		{"parent dir staged name", filepath.Join(appDir, "..", stagingPrefix+".exe"), false},
		{"absolute path outside", filepath.Join(filepath.VolumeName(appDir)+string(filepath.Separator), stagingPrefix+".exe"), false},
		{"empty", "", false},
		{"whitespace", "   ", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := isUpdateArtifact(tc.path); got != tc.want {
				t.Fatalf("isUpdateArtifact(%q) = %v, want %v", tc.path, got, tc.want)
			}
		})
	}
}

func TestVerifyArtifact(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "payload.bin")
	content := []byte("cczj video update payload")
	if err := os.WriteFile(path, content, 0644); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(content)
	good := hex.EncodeToString(sum[:])

	if err := verifyArtifact(path, good); err != nil {
		t.Fatalf("expected match, got %v", err)
	}
	// 大小写不敏感：清单里的摘要可能写成大写。
	if err := verifyArtifact(path, strings.ToUpper(good)); err != nil {
		t.Fatalf("expected case-insensitive match, got %v", err)
	}
	if err := verifyArtifact(path, strings.Repeat("0", 64)); err == nil {
		t.Fatal("expected mismatch to fail")
	}
	// 没有期望摘要时必须失败，不能"跳过校验"当成通过。
	if err := verifyArtifact(path, ""); err == nil {
		t.Fatal("expected empty expectation to fail")
	}
	if err := verifyArtifact(filepath.Join(dir, "missing.bin"), good); err == nil {
		t.Fatal("expected missing file to fail")
	}
}

func TestScanAlreadyDownloadedFindsStagedArtifact(t *testing.T) {
	dir := t.TempDir()
	// scanAlreadyDownloaded 只看真实应用目录，这里只验证命名规则与 glob 一致。
	staged := filepath.Join(dir, updateStagingName("https://github.com/ws-cczj/CCZJ-Video/releases/download/v2.2.1/app.zip"))
	if err := os.WriteFile(staged, []byte(strings.Repeat("x", 2048)), 0644); err != nil {
		t.Fatal(err)
	}
	matches, err := filepath.Glob(filepath.Join(dir, stagingPrefix+".*"))
	if err != nil || len(matches) != 1 {
		t.Fatalf("staged artifact is not discoverable by the scan pattern: %v %v", matches, err)
	}
	if matches[0] != staged {
		t.Fatalf("glob matched %v, want %v", matches[0], staged)
	}
}

// "已下载"入口可以绕过整个下载校验层：产物名字对、文件存在，就直接递给 InstallUpdate
// 执行。所以校验过的字节必须留下一张凭据，装之前再核一遍——核不过就什么都不许动。
func TestDigestRecordGatesInstall(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, stagingPrefix+".exe")
	if err := os.WriteFile(path, []byte("payload"), 0644); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256([]byte("payload"))
	good := hex.EncodeToString(sum[:])

	if err := verifyRecordedArtifact(path); err == nil {
		t.Fatal("没有摘要记录时必须拒绝安装，不能只凭文件名就 exec")
	}
	if hasDigestRecord(path) {
		t.Fatal("还没写过凭据不该被认作有凭据")
	}

	if err := recordDigest(path, good); err != nil {
		t.Fatal(err)
	}
	if !hasDigestRecord(path) {
		t.Fatal("凭据已写入，hasDigestRecord 应认")
	}
	if err := verifyRecordedArtifact(path); err != nil {
		t.Fatalf("凭据相符应通过: %v", err)
	}

	// 产物被换过（下载截断、别的程序改写）之后，旧凭据不能继续给它背书。
	if err := os.WriteFile(path, []byte("trunc"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := verifyRecordedArtifact(path); err == nil {
		t.Fatal("内容与凭据不符时应拒绝安装")
	}

	clearDigestRecord(path)
	if hasDigestRecord(path) || fileExists(digestRecordPath(path)) {
		t.Fatal("清理后不该留下凭据")
	}

	// 凭据格式不对等于没有：半截摘要既不能通过也不能被当成"跳过校验"。
	if err := os.WriteFile(digestRecordPath(path), []byte("not-a-digest\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if hasDigestRecord(path) {
		t.Fatal("非法摘要记录不该被认作凭据")
	}
	if err := verifyRecordedArtifact(path); err == nil {
		t.Fatal("非法摘要记录应拒绝安装")
	}
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
