// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export class CollectReq {
    /**
     * Creates a new CollectReq instance.
     * @param {Partial<CollectReq>} [$$source = {}] - The source object to create the CollectReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * "full" | "incremental" | "once"（空=full）
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("hours" in $$source)) {
            /**
             * 增量模式的回溯小时数（空=使用源配置）
             * @member
             * @type {number}
             */
            this["hours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectReq(/** @type {Partial<CollectReq>} */($$parsedSource));
    }
}

/**
 * CollectScheduleConfig 采集调度配置（持久化到 settings 表）
 */
export class CollectScheduleConfig {
    /**
     * Creates a new CollectScheduleConfig instance.
     * @param {Partial<CollectScheduleConfig>} [$$source = {}] - The source object to create the CollectScheduleConfig.
     */
    constructor($$source = {}) {
        if (!("enable_background" in $$source)) {
            /**
             * 是否启用后台周期采集
             * @member
             * @type {boolean}
             */
            this["enable_background"] = false;
        }
        if (!("background_interval_seconds" in $$source)) {
            /**
             * 后台周期采集间隔（秒），默认 60
             * @member
             * @type {number}
             */
            this["background_interval_seconds"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 向后兼容字段：旧版分钟（会在读取时转换为 seconds）
             * @member
             * @type {number | undefined}
             */
            this["background_interval_minutes"] = undefined;
        }
        if (!("enable_startup_catchup" in $$source)) {
            /**
             * 是否在软件启动时执行"从上次退出时间到现在"的补采
             * @member
             * @type {boolean}
             */
            this["enable_startup_catchup"] = false;
        }
        if (!("enable_initial_full_collect" in $$source)) {
            /**
             * 启动后首次全量采集是否启用（初始化数据库）
             * @member
             * @type {boolean}
             */
            this["enable_initial_full_collect"] = false;
        }
        if (!("source_gap_seconds" in $$source)) {
            /**
             * 顺序采集两个 source 之间的最小间隔（秒）
             * @member
             * @type {number}
             */
            this["source_gap_seconds"] = 0;
        }
        if (!("page_gap_seconds" in $$source)) {
            /**
             * 每页之间等待秒数（覆盖 engine 默认的 30s）
             * @member
             * @type {number}
             */
            this["page_gap_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectScheduleConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectScheduleConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectScheduleConfig(/** @type {Partial<CollectScheduleConfig>} */($$parsedSource));
    }
}

/**
 * CollectStatus 暴露给前端的采集状态
 */
export class CollectStatus {
    /**
     * Creates a new CollectStatus instance.
     * @param {Partial<CollectStatus>} [$$source = {}] - The source object to create the CollectStatus.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * 当前正在采集的页码
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("names" in $$source)) {
            /**
             * 当前页的视频名称
             * @member
             * @type {string[]}
             */
            this["names"] = [];
        }
        if (!("log" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["log"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * 当前采集模式
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectStatus}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField6_0($$parsedSource["names"]);
        }
        return new CollectStatus(/** @type {Partial<CollectStatus>} */($$parsedSource));
    }
}

export class DeleteVideoReq {
    /**
     * Creates a new DeleteVideoReq instance.
     * @param {Partial<DeleteVideoReq>} [$$source = {}] - The source object to create the DeleteVideoReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteVideoReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeleteVideoReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteVideoReq(/** @type {Partial<DeleteVideoReq>} */($$parsedSource));
    }
}

export class GetTypesReq {
    /**
     * Creates a new GetTypesReq instance.
     * @param {Partial<GetTypesReq>} [$$source = {}] - The source object to create the GetTypesReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetTypesReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetTypesReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetTypesReq(/** @type {Partial<GetTypesReq>} */($$parsedSource));
    }
}

/**
 * HistoryItemWithVideo 前端可用的"继续观看"条目：含视频名+封面，便于卡片展示
 */
export class HistoryItemWithVideo {
    /**
     * Creates a new HistoryItemWithVideo instance.
     * @param {Partial<HistoryItemWithVideo>} [$$source = {}] - The source object to create the HistoryItemWithVideo.
     */
    constructor($$source = {}) {
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("ep_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ep_num"] = 0;
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("vod_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_name"] = "";
        }
        if (!("vod_pic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_pic"] = "";
        }
        if (!("vod_remarks" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_remarks"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryItemWithVideo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryItemWithVideo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryItemWithVideo(/** @type {Partial<HistoryItemWithVideo>} */($$parsedSource));
    }
}

/**
 * Status 调度器状态（供前端展示）
 */
export class SchedulerStatus {
    /**
     * Creates a new SchedulerStatus instance.
     * @param {Partial<SchedulerStatus>} [$$source = {}] - The source object to create the SchedulerStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("background" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["background"] = false;
        }
        if (!("background_every_minutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["background_every_minutes"] = 0;
        }
        if (!("background_every_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["background_every_seconds"] = 0;
        }
        if (!("source_gap_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["source_gap_seconds"] = 0;
        }
        if (!("page_gap_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_gap_seconds"] = 0;
        }
        if (!("last_exit_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_exit_unix"] = 0;
        }
        if (!("last_run_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_run_unix"] = 0;
        }
        if (!("now_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["now_unix"] = 0;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("source_schedules" in $$source)) {
            /**
             * @member
             * @type {SourceScheduleItem[]}
             */
            this["source_schedules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulerStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulerStatus}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source_schedules" in $$parsedSource) {
            $$parsedSource["source_schedules"] = $$createField10_0($$parsedSource["source_schedules"]);
        }
        return new SchedulerStatus(/** @type {Partial<SchedulerStatus>} */($$parsedSource));
    }
}

/**
 * ============================================================
 * SearchSource: 用 wd=keyword 去源站模糊搜索，把结果入库，并返回
 * ============================================================
 */
export class SearchSourceResult {
    /**
     * Creates a new SearchSourceResult instance.
     * @param {Partial<SearchSourceResult>} [$$source = {}] - The source object to create the SearchSourceResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("videos" in $$source)) {
            /**
             * @member
             * @type {(model$0.Video | null)[]}
             */
            this["videos"] = [];
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchSourceResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchSourceResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("videos" in $$parsedSource) {
            $$parsedSource["videos"] = $$createField1_0($$parsedSource["videos"]);
        }
        return new SearchSourceResult(/** @type {Partial<SearchSourceResult>} */($$parsedSource));
    }
}

/**
 * SourceDetail 返回该源的"字段 + 示例"，用于设置页面展示
 */
export class SourceDetail {
    /**
     * Creates a new SourceDetail instance.
     * @param {Partial<SourceDetail>} [$$source = {}] - The source object to create the SourceDetail.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("api_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_url"] = "";
        }
        if (!("tables" in $$source)) {
            /**
             * @member
             * @type {SourceTableSummary[]}
             */
            this["tables"] = [];
        }
        if (!("sample_videos" in $$source)) {
            /**
             * @member
             * @type {(model$0.Video | null)[]}
             */
            this["sample_videos"] = [];
        }
        if (!("sample_episodes" in $$source)) {
            /**
             * @member
             * @type {(model$0.Episode | null)[]}
             */
            this["sample_episodes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceDetail}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField3_0($$parsedSource["tables"]);
        }
        if ("sample_videos" in $$parsedSource) {
            $$parsedSource["sample_videos"] = $$createField4_0($$parsedSource["sample_videos"]);
        }
        if ("sample_episodes" in $$parsedSource) {
            $$parsedSource["sample_episodes"] = $$createField5_0($$parsedSource["sample_episodes"]);
        }
        return new SourceDetail(/** @type {Partial<SourceDetail>} */($$parsedSource));
    }
}

/**
 * ============================================================
 * GetSourceParams: 返回采集接口参数规范（给前端规则指南用）
 * ============================================================
 */
export class SourceParamDoc {
    /**
     * Creates a new SourceParamDoc instance.
     * @param {Partial<SourceParamDoc>} [$$source = {}] - The source object to create the SourceParamDoc.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desc"] = "";
        }
        if (!("example" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["example"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceParamDoc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceParamDoc}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceParamDoc(/** @type {Partial<SourceParamDoc>} */($$parsedSource));
    }
}

export class SourceParamsDoc {
    /**
     * Creates a new SourceParamsDoc instance.
     * @param {Partial<SourceParamsDoc>} [$$source = {}] - The source object to create the SourceParamsDoc.
     */
    constructor($$source = {}) {
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }
        if (!("path_params" in $$source)) {
            /**
             * @member
             * @type {SourceParamDoc[]}
             */
            this["path_params"] = [];
        }
        if (!("query_ac" in $$source)) {
            /**
             * @member
             * @type {SourceParamDoc[]}
             */
            this["query_ac"] = [];
        }
        if (!("query_common" in $$source)) {
            /**
             * @member
             * @type {SourceParamDoc[]}
             */
            this["query_common"] = [];
        }
        if (!("query_advanced" in $$source)) {
            /**
             * @member
             * @type {SourceParamDoc[]}
             */
            this["query_advanced"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceParamsDoc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceParamsDoc}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path_params" in $$parsedSource) {
            $$parsedSource["path_params"] = $$createField1_0($$parsedSource["path_params"]);
        }
        if ("query_ac" in $$parsedSource) {
            $$parsedSource["query_ac"] = $$createField2_0($$parsedSource["query_ac"]);
        }
        if ("query_common" in $$parsedSource) {
            $$parsedSource["query_common"] = $$createField3_0($$parsedSource["query_common"]);
        }
        if ("query_advanced" in $$parsedSource) {
            $$parsedSource["query_advanced"] = $$createField4_0($$parsedSource["query_advanced"]);
        }
        return new SourceParamsDoc(/** @type {Partial<SourceParamsDoc>} */($$parsedSource));
    }
}

/**
 * SourceScheduleItem 单个源的调度信息
 */
export class SourceScheduleItem {
    /**
     * Creates a new SourceScheduleItem instance.
     * @param {Partial<SourceScheduleItem>} [$$source = {}] - The source object to create the SourceScheduleItem.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("mode" in $$source)) {
            /**
             * full | incremental
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("interval_min" in $$source)) {
            /**
             * 定时间隔（分钟）
             * @member
             * @type {number}
             */
            this["interval_min"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * 是否正在采集
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceScheduleItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceScheduleItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceScheduleItem(/** @type {Partial<SourceScheduleItem>} */($$parsedSource));
    }
}

/**
 * SourceScheduleReq 设置单个源的调度配置请求
 */
export class SourceScheduleReq {
    /**
     * Creates a new SourceScheduleReq instance.
     * @param {Partial<SourceScheduleReq>} [$$source = {}] - The source object to create the SourceScheduleReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("mode" in $$source)) {
            /**
             * full | incremental
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("interval_min" in $$source)) {
            /**
             * 定时间隔（分钟），最小 5
             * @member
             * @type {number}
             */
            this["interval_min"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceScheduleReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceScheduleReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceScheduleReq(/** @type {Partial<SourceScheduleReq>} */($$parsedSource));
    }
}

/**
 * SourceTableSummary 描述该源下某一张表的信息
 */
export class SourceTableSummary {
    /**
     * Creates a new SourceTableSummary instance.
     * @param {Partial<SourceTableSummary>} [$$source = {}] - The source object to create the SourceTableSummary.
     */
    constructor($$source = {}) {
        if (!("table_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table_name"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * video / episode / type
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("row_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["row_count"] = 0;
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {db$0.TableColumn[]}
             */
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceTableSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceTableSummary}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        return new SourceTableSummary(/** @type {Partial<SourceTableSummary>} */($$parsedSource));
    }
}

export class VideoDetailReq {
    /**
     * Creates a new VideoDetailReq instance.
     * @param {Partial<VideoDetailReq>} [$$source = {}] - The source object to create the VideoDetailReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("refresh" in $$source)) {
            /**
             * 为 true 时先从源站拉取最新数据再返回
             * @member
             * @type {boolean}
             */
            this["refresh"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoDetailReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoDetailReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoDetailReq(/** @type {Partial<VideoDetailReq>} */($$parsedSource));
    }
}

export class VideoDetailResp {
    /**
     * Creates a new VideoDetailResp instance.
     * @param {Partial<VideoDetailResp>} [$$source = {}] - The source object to create the VideoDetailResp.
     */
    constructor($$source = {}) {
        if (!("video" in $$source)) {
            /**
             * @member
             * @type {model$0.Video | null}
             */
            this["video"] = null;
        }
        if (!("episodes" in $$source)) {
            /**
             * @member
             * @type {(model$0.Episode | null)[]}
             */
            this["episodes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoDetailResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoDetailResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("video" in $$parsedSource) {
            $$parsedSource["video"] = $$createField0_0($$parsedSource["video"]);
        }
        if ("episodes" in $$parsedSource) {
            $$parsedSource["episodes"] = $$createField1_0($$parsedSource["episodes"]);
        }
        return new VideoDetailResp(/** @type {Partial<VideoDetailResp>} */($$parsedSource));
    }
}

export class VideoListReq {
    /**
     * Creates a new VideoListReq instance.
     * @param {Partial<VideoListReq>} [$$source = {}] - The source object to create the VideoListReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("type_id" in $$source)) {
            /**
             * type_id 同时支持字符串与数字，保存为字符串
             * @member
             * @type {string}
             */
            this["type_id"] = "";
        }
        if (!("year" in $$source)) {
            /**
             * 年份筛选（"all" 或具体年份）
             * @member
             * @type {string}
             */
            this["year"] = "";
        }
        if (!("area" in $$source)) {
            /**
             * 地区筛选（"all" 或具体地区）
             * @member
             * @type {string}
             */
            this["area"] = "";
        }
        if (!("keyword" in $$source)) {
            /**
             * 关键词：标题/演员/导演/备注/年份/地区/类型 模糊匹配
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }
        if (!("sort" in $$source)) {
            /**
             * "" 默认; "rating" 按评分; "hot" 按热度
             * @member
             * @type {string}
             */
            this["sort"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoListReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoListReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoListReq(/** @type {Partial<VideoListReq>} */($$parsedSource));
    }
}

export class VideoListResp {
    /**
     * Creates a new VideoListResp instance.
     * @param {Partial<VideoListResp>} [$$source = {}] - The source object to create the VideoListResp.
     */
    constructor($$source = {}) {
        if (!("videos" in $$source)) {
            /**
             * @member
             * @type {(model$0.Video | null)[]}
             */
            this["videos"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoListResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoListResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("videos" in $$parsedSource) {
            $$parsedSource["videos"] = $$createField0_0($$parsedSource["videos"]);
        }
        return new VideoListResp(/** @type {Partial<VideoListResp>} */($$parsedSource));
    }
}

export class VideoSearchReq {
    /**
     * Creates a new VideoSearchReq instance.
     * @param {Partial<VideoSearchReq>} [$$source = {}] - The source object to create the VideoSearchReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoSearchReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoSearchReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoSearchReq(/** @type {Partial<VideoSearchReq>} */($$parsedSource));
    }
}

/**
 * YearAreaResp 前端用于前端：返回所有可选年份 / 地区列表（用于筛选下拉框的选项）
 */
export class YearsResp {
    /**
     * Creates a new YearsResp instance.
     * @param {Partial<YearsResp>} [$$source = {}] - The source object to create the YearsResp.
     */
    constructor($$source = {}) {
        if (!("years" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["years"] = [];
        }
        if (!("areas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["areas"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new YearsResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {YearsResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("years" in $$parsedSource) {
            $$parsedSource["years"] = $$createField0_0($$parsedSource["years"]);
        }
        if ("areas" in $$parsedSource) {
            $$parsedSource["areas"] = $$createField1_0($$parsedSource["areas"]);
        }
        return new YearsResp(/** @type {Partial<YearsResp>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SourceScheduleItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.Video.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SourceTableSummary.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.Episode.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = SourceParamDoc.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = db$0.TableColumn.createFrom;
const $$createType14 = $Create.Array($$createType13);
