// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as detail$0 from "../detail/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export class CollectReq {
    /**
     * Creates a new CollectReq instance.
     * @param {Partial<CollectReq>} [$$source = {}] - The source object to create the CollectReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * "full" | "incremental" | "once"（空=full）
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("hours" in $$source)) {
            /**
             * 增量模式的回溯小时数（空=使用源配置）
             * @member
             * @type {number}
             */
            this["hours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectReq(/** @type {Partial<CollectReq>} */($$parsedSource));
    }
}

/**
 * CollectScheduleConfig 采集调度配置（持久化到 settings 表）
 */
export class CollectScheduleConfig {
    /**
     * Creates a new CollectScheduleConfig instance.
     * @param {Partial<CollectScheduleConfig>} [$$source = {}] - The source object to create the CollectScheduleConfig.
     */
    constructor($$source = {}) {
        if (!("enable_background" in $$source)) {
            /**
             * 是否启用后台周期采集
             * @member
             * @type {boolean}
             */
            this["enable_background"] = false;
        }
        if (!("background_interval_seconds" in $$source)) {
            /**
             * 后台周期采集间隔（秒），默认 60
             * @member
             * @type {number}
             */
            this["background_interval_seconds"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 向后兼容字段：旧版分钟（会在读取时转换为 seconds）
             * @member
             * @type {number | undefined}
             */
            this["background_interval_minutes"] = undefined;
        }
        if (!("enable_startup_catchup" in $$source)) {
            /**
             * 是否在软件启动时执行"从上次退出时间到现在"的补采
             * @member
             * @type {boolean}
             */
            this["enable_startup_catchup"] = false;
        }
        if (!("enable_initial_full_collect" in $$source)) {
            /**
             * 启动后首次全量采集是否启用（初始化数据库）
             * @member
             * @type {boolean}
             */
            this["enable_initial_full_collect"] = false;
        }
        if (!("source_gap_seconds" in $$source)) {
            /**
             * 顺序采集两个 source 之间的最小间隔（秒）
             * @member
             * @type {number}
             */
            this["source_gap_seconds"] = 0;
        }
        if (!("page_gap_seconds" in $$source)) {
            /**
             * 每页之间等待秒数（覆盖 engine 默认的 30s）
             * @member
             * @type {number}
             */
            this["page_gap_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectScheduleConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectScheduleConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectScheduleConfig(/** @type {Partial<CollectScheduleConfig>} */($$parsedSource));
    }
}

/**
 * CollectStatus 暴露给前端的采集状态
 */
export class CollectStatus {
    /**
     * Creates a new CollectStatus instance.
     * @param {Partial<CollectStatus>} [$$source = {}] - The source object to create the CollectStatus.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * 当前正在采集的页码
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("names" in $$source)) {
            /**
             * 当前页的视频名称
             * @member
             * @type {string[]}
             */
            this["names"] = [];
        }
        if (!("log" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["log"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * 当前采集模式
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("saved" in $$source)) {
            /**
             * 上一次运行的结果：进度字段只描述"正在跑的这一次"，运行结束后必须由
             * 这组字段说明这次到底完成了多少、哪些页没落地。
             * @member
             * @type {number}
             */
            this["saved"] = 0;
        }
        if (!("fetch_failures" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["fetch_failures"] = [];
        }
        if (!("save_failures" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["save_failures"] = [];
        }
        if (!("empty_pages" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["empty_pages"] = [];
        }
        if (!("last_error_kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_error_kind"] = "";
        }
        if (!("elapsed_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsed_ms"] = 0;
        }
        if (!("finished_at_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["finished_at_unix"] = 0;
        }
        if (!("stopped" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["stopped"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectStatus}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField6_0($$parsedSource["names"]);
        }
        if ("fetch_failures" in $$parsedSource) {
            $$parsedSource["fetch_failures"] = $$createField10_0($$parsedSource["fetch_failures"]);
        }
        if ("save_failures" in $$parsedSource) {
            $$parsedSource["save_failures"] = $$createField11_0($$parsedSource["save_failures"]);
        }
        if ("empty_pages" in $$parsedSource) {
            $$parsedSource["empty_pages"] = $$createField12_0($$parsedSource["empty_pages"]);
        }
        return new CollectStatus(/** @type {Partial<CollectStatus>} */($$parsedSource));
    }
}

export class DeleteVideoReq {
    /**
     * Creates a new DeleteVideoReq instance.
     * @param {Partial<DeleteVideoReq>} [$$source = {}] - The source object to create the DeleteVideoReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteVideoReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeleteVideoReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteVideoReq(/** @type {Partial<DeleteVideoReq>} */($$parsedSource));
    }
}

export class GetTypesReq {
    /**
     * Creates a new GetTypesReq instance.
     * @param {Partial<GetTypesReq>} [$$source = {}] - The source object to create the GetTypesReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetTypesReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GetTypesReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetTypesReq(/** @type {Partial<GetTypesReq>} */($$parsedSource));
    }
}

/**
 * HistoryItemWithVideo 前端可用的"继续观看"条目：含视频名+封面，便于卡片展示
 */
export class HistoryItemWithVideo {
    /**
     * Creates a new HistoryItemWithVideo instance.
     * @param {Partial<HistoryItemWithVideo>} [$$source = {}] - The source object to create the HistoryItemWithVideo.
     */
    constructor($$source = {}) {
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("ep_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ep_num"] = 0;
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("vod_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_name"] = "";
        }
        if (!("vod_pic" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_pic"] = "";
        }
        if (!("vod_remarks" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_remarks"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryItemWithVideo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryItemWithVideo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryItemWithVideo(/** @type {Partial<HistoryItemWithVideo>} */($$parsedSource));
    }
}

/**
 * MergeCandidatesResp 是待人工确认的疑似重复身份组。
 */
export class MergeCandidatesResp {
    /**
     * Creates a new MergeCandidatesResp instance.
     * @param {Partial<MergeCandidatesResp>} [$$source = {}] - The source object to create the MergeCandidatesResp.
     */
    constructor($$source = {}) {
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {db$0.MergeCandidate[]}
             */
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeCandidatesResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeCandidatesResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        return new MergeCandidatesResp(/** @type {Partial<MergeCandidatesResp>} */($$parsedSource));
    }
}

/**
 * MergeIdentitiesReq 指定一组要合并的 global_id。一次一组，不做批量勾选：
 * 合并会搬走收藏和观看进度，接受一次点错的代价太高。
 */
export class MergeIdentitiesReq {
    /**
     * Creates a new MergeIdentitiesReq instance.
     * @param {Partial<MergeIdentitiesReq>} [$$source = {}] - The source object to create the MergeIdentitiesReq.
     */
    constructor($$source = {}) {
        if (!("global_ids" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["global_ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeIdentitiesReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeIdentitiesReq}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("global_ids" in $$parsedSource) {
            $$parsedSource["global_ids"] = $$createField0_0($$parsedSource["global_ids"]);
        }
        return new MergeIdentitiesReq(/** @type {Partial<MergeIdentitiesReq>} */($$parsedSource));
    }
}

/**
 * MergeIdentitiesResp 报告存活身份与被并掉的条数。
 */
export class MergeIdentitiesResp {
    /**
     * Creates a new MergeIdentitiesResp instance.
     * @param {Partial<MergeIdentitiesResp>} [$$source = {}] - The source object to create the MergeIdentitiesResp.
     */
    constructor($$source = {}) {
        if (!("keep_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keep_id"] = 0;
        }
        if (!("merged" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["merged"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeIdentitiesResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeIdentitiesResp}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeIdentitiesResp(/** @type {Partial<MergeIdentitiesResp>} */($$parsedSource));
    }
}

/**
 * PlayLineSpeedItem 是一条线路的测速结果。Error 只写日志，不下发给界面。
 */
export class PlayLineSpeedItem {
    /**
     * Creates a new PlayLineSpeedItem instance.
     * @param {Partial<PlayLineSpeedItem>} [$$source = {}] - The source object to create the PlayLineSpeedItem.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ep_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ep_num"] = 0;
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency_ms"] = 0;
        }
        if (!("bytes_per_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_per_sec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayLineSpeedItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayLineSpeedItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayLineSpeedItem(/** @type {Partial<PlayLineSpeedItem>} */($$parsedSource));
    }
}

/**
 * PlayLineSpeedReq 定位一次测速。播放地址不在请求里：由服务端按同一份详情解析，
 * 免得前端把地址传回来再解析一遍，两边口径还可能不一致。
 */
export class PlayLineSpeedReq {
    /**
     * Creates a new PlayLineSpeedReq instance.
     * @param {Partial<PlayLineSpeedReq>} [$$source = {}] - The source object to create the PlayLineSpeedReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("ep_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ep_num"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayLineSpeedReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayLineSpeedReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayLineSpeedReq(/** @type {Partial<PlayLineSpeedReq>} */($$parsedSource));
    }
}

/**
 * PlayLineSpeedResp 的 Items 已按「可用优先 → 吞吐高优先 → 延迟低优先」排好，
 * 界面可以直接照序渲染；BestIndex 为 -1 表示没有任何一条线路可用。
 */
export class PlayLineSpeedResp {
    /**
     * Creates a new PlayLineSpeedResp instance.
     * @param {Partial<PlayLineSpeedResp>} [$$source = {}] - The source object to create the PlayLineSpeedResp.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {(PlayLineSpeedItem | null)[]}
             */
            this["items"] = [];
        }
        if (!("best_index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["best_index"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayLineSpeedResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayLineSpeedResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new PlayLineSpeedResp(/** @type {Partial<PlayLineSpeedResp>} */($$parsedSource));
    }
}

/**
 * RecycleListReq 是回收站分页请求。SourceKey 为空表示跨源列出全部。
 */
export class RecycleListReq {
    /**
     * Creates a new RecycleListReq instance.
     * @param {Partial<RecycleListReq>} [$$source = {}] - The source object to create the RecycleListReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleListReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleListReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecycleListReq(/** @type {Partial<RecycleListReq>} */($$parsedSource));
    }
}

/**
 * RecycleListResp 是回收站一页加总数。
 */
export class RecycleListResp {
    /**
     * Creates a new RecycleListResp instance.
     * @param {Partial<RecycleListResp>} [$$source = {}] - The source object to create the RecycleListResp.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {db$0.RecycleItem[]}
             */
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleListResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleListResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new RecycleListResp(/** @type {Partial<RecycleListResp>} */($$parsedSource));
    }
}

/**
 * RecycleReq 定位一条回收站条目。回收站跨源，所以源坐标是必填的。
 */
export class RecycleReq {
    /**
     * Creates a new RecycleReq instance.
     * @param {Partial<RecycleReq>} [$$source = {}] - The source object to create the RecycleReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecycleReq(/** @type {Partial<RecycleReq>} */($$parsedSource));
    }
}

/**
 * RecycleResult 是一次彻底删除/清空的结果。
 */
export class RecycleResult {
    /**
     * Creates a new RecycleResult instance.
     * @param {Partial<RecycleResult>} [$$source = {}] - The source object to create the RecycleResult.
     */
    constructor($$source = {}) {
        if (!("affected" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["affected"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecycleResult(/** @type {Partial<RecycleResult>} */($$parsedSource));
    }
}

/**
 * Status 调度器状态（供前端展示）
 */
export class SchedulerStatus {
    /**
     * Creates a new SchedulerStatus instance.
     * @param {Partial<SchedulerStatus>} [$$source = {}] - The source object to create the SchedulerStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("background" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["background"] = false;
        }
        if (!("background_every_minutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["background_every_minutes"] = 0;
        }
        if (!("background_every_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["background_every_seconds"] = 0;
        }
        if (!("source_gap_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["source_gap_seconds"] = 0;
        }
        if (!("page_gap_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_gap_seconds"] = 0;
        }
        if (!("startup_catchup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startup_catchup"] = false;
        }
        if (!("initial_full_collect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["initial_full_collect"] = false;
        }
        if (!("last_exit_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_exit_unix"] = 0;
        }
        if (!("last_run_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_run_unix"] = 0;
        }
        if (!("now_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["now_unix"] = 0;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("source_schedules" in $$source)) {
            /**
             * @member
             * @type {SourceScheduleItem[]}
             */
            this["source_schedules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulerStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulerStatus}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source_schedules" in $$parsedSource) {
            $$parsedSource["source_schedules"] = $$createField12_0($$parsedSource["source_schedules"]);
        }
        return new SchedulerStatus(/** @type {Partial<SchedulerStatus>} */($$parsedSource));
    }
}

/**
 * ============================================================
 * SearchSource: 用 wd=keyword 去源站搜索指定页，返回富字段结果（不入库）
 * 入库请调用 ImportSourceVideos
 * ============================================================
 */
export class SearchSourceResult {
    /**
     * Creates a new SearchSourceResult instance.
     * @param {Partial<SearchSourceResult>} [$$source = {}] - The source object to create the SearchSourceResult.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_count"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }
        if (!("videos" in $$source)) {
            /**
             * @member
             * @type {(model$0.Video | null)[]}
             */
            this["videos"] = [];
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchSourceResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchSourceResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("videos" in $$parsedSource) {
            $$parsedSource["videos"] = $$createField4_0($$parsedSource["videos"]);
        }
        return new SearchSourceResult(/** @type {Partial<SearchSourceResult>} */($$parsedSource));
    }
}

/**
 * SourceDetail 返回该源的"字段 + 示例"，用于设置页面展示
 */
export class SourceDetail {
    /**
     * Creates a new SourceDetail instance.
     * @param {Partial<SourceDetail>} [$$source = {}] - The source object to create the SourceDetail.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("api_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_url"] = "";
        }
        if (!("tables" in $$source)) {
            /**
             * @member
             * @type {SourceTableSummary[]}
             */
            this["tables"] = [];
        }
        if (!("sample_videos" in $$source)) {
            /**
             * @member
             * @type {(model$0.Video | null)[]}
             */
            this["sample_videos"] = [];
        }
        if (!("sample_episodes" in $$source)) {
            /**
             * @member
             * @type {(model$0.Episode | null)[]}
             */
            this["sample_episodes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceDetail}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType16;
        const $$createField4_0 = $$createType14;
        const $$createField5_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField3_0($$parsedSource["tables"]);
        }
        if ("sample_videos" in $$parsedSource) {
            $$parsedSource["sample_videos"] = $$createField4_0($$parsedSource["sample_videos"]);
        }
        if ("sample_episodes" in $$parsedSource) {
            $$parsedSource["sample_episodes"] = $$createField5_0($$parsedSource["sample_episodes"]);
        }
        return new SourceDetail(/** @type {Partial<SourceDetail>} */($$parsedSource));
    }
}

/**
 * ============================================================
 * GetSourceParams: 返回采集接口参数规范（给前端规则指南用）
 * ============================================================
 */
export class SourceParamDoc {
    /**
     * Creates a new SourceParamDoc instance.
     * @param {Partial<SourceParamDoc>} [$$source = {}] - The source object to create the SourceParamDoc.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["desc"] = "";
        }
        if (!("example" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["example"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceParamDoc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceParamDoc}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceParamDoc(/** @type {Partial<SourceParamDoc>} */($$parsedSource));
    }
}

export class SourceParamsDoc {
    /**
     * Creates a new SourceParamsDoc instance.
     * @param {Partial<SourceParamsDoc>} [$$source = {}] - The source object to create the SourceParamsDoc.
     */
    constructor($$source = {}) {
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }
        if (!("path_params" in $$source)) {
            /**
             * @member
             * @type {SourceParamDoc[]}
             */
            this["path_params"] = [];
        }
        if (!("query_ac" in $$source)) {
            /**
             * @member
             * @type {SourceParamDoc[]}
             */
            this["query_ac"] = [];
        }
        if (!("query_common" in $$source)) {
            /**
             * @member
             * @type {SourceParamDoc[]}
             */
            this["query_common"] = [];
        }
        if (!("query_advanced" in $$source)) {
            /**
             * @member
             * @type {SourceParamDoc[]}
             */
            this["query_advanced"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceParamsDoc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceParamsDoc}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType21;
        const $$createField2_0 = $$createType21;
        const $$createField3_0 = $$createType21;
        const $$createField4_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path_params" in $$parsedSource) {
            $$parsedSource["path_params"] = $$createField1_0($$parsedSource["path_params"]);
        }
        if ("query_ac" in $$parsedSource) {
            $$parsedSource["query_ac"] = $$createField2_0($$parsedSource["query_ac"]);
        }
        if ("query_common" in $$parsedSource) {
            $$parsedSource["query_common"] = $$createField3_0($$parsedSource["query_common"]);
        }
        if ("query_advanced" in $$parsedSource) {
            $$parsedSource["query_advanced"] = $$createField4_0($$parsedSource["query_advanced"]);
        }
        return new SourceParamsDoc(/** @type {Partial<SourceParamsDoc>} */($$parsedSource));
    }
}

/**
 * SourceScheduleItem 单个源的调度信息
 */
export class SourceScheduleItem {
    /**
     * Creates a new SourceScheduleItem instance.
     * @param {Partial<SourceScheduleItem>} [$$source = {}] - The source object to create the SourceScheduleItem.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("mode" in $$source)) {
            /**
             * full | incremental
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("interval_min" in $$source)) {
            /**
             * 定时间隔（分钟）
             * @member
             * @type {number}
             */
            this["interval_min"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * 是否正在采集
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("covered_until_unix" in $$source)) {
            /**
             * 增量水位线：已覆盖到 / 最近一次尝试采集的时刻（unix 秒，0 表示没有记录）
             * @member
             * @type {number}
             */
            this["covered_until_unix"] = 0;
        }
        if (!("last_attempt_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_attempt_unix"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceScheduleItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceScheduleItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceScheduleItem(/** @type {Partial<SourceScheduleItem>} */($$parsedSource));
    }
}

/**
 * SourceScheduleReq 设置单个源的调度配置请求
 */
export class SourceScheduleReq {
    /**
     * Creates a new SourceScheduleReq instance.
     * @param {Partial<SourceScheduleReq>} [$$source = {}] - The source object to create the SourceScheduleReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("mode" in $$source)) {
            /**
             * full | incremental
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("interval_min" in $$source)) {
            /**
             * 定时间隔（分钟），最小 5
             * @member
             * @type {number}
             */
            this["interval_min"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceScheduleReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceScheduleReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceScheduleReq(/** @type {Partial<SourceScheduleReq>} */($$parsedSource));
    }
}

/**
 * SourceTableSummary 描述该源下某一张表的信息
 */
export class SourceTableSummary {
    /**
     * Creates a new SourceTableSummary instance.
     * @param {Partial<SourceTableSummary>} [$$source = {}] - The source object to create the SourceTableSummary.
     */
    constructor($$source = {}) {
        if (!("table_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table_name"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * video / episode / type
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("row_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["row_count"] = 0;
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {db$0.TableColumn[]}
             */
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceTableSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceTableSummary}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        return new SourceTableSummary(/** @type {Partial<SourceTableSummary>} */($$parsedSource));
    }
}

/**
 * UnionListReq 是跨源合并列表的筛选条件。没有 source_key 是有意为之：
 * 这个视图的意义就是跨源，想只看一个源请回到视频库。
 */
export class UnionListReq {
    /**
     * Creates a new UnionListReq instance.
     * @param {Partial<UnionListReq>} [$$source = {}] - The source object to create the UnionListReq.
     */
    constructor($$source = {}) {
        if (!("recent_days" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["recent_days"] = 0;
        }
        if (!("type_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type_id"] = "";
        }
        if (!("year" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["year"] = "";
        }
        if (!("area" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["area"] = "";
        }
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }
        if (!("cursor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cursor"] = "";
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnionListReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnionListReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnionListReq(/** @type {Partial<UnionListReq>} */($$parsedSource));
    }
}

/**
 * UnionListResp 是一页合并卡片。Total 数的是身份数而不是目录行数，
 * 所以它会比同筛选下的单源列表小——这正是"合并"要达到的效果。
 */
export class UnionListResp {
    /**
     * Creates a new UnionListResp instance.
     * @param {Partial<UnionListResp>} [$$source = {}] - The source object to create the UnionListResp.
     */
    constructor($$source = {}) {
        if (!("videos" in $$source)) {
            /**
             * @member
             * @type {(db$0.UnionVideo | null)[]}
             */
            this["videos"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("next_cursor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["next_cursor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnionListResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnionListResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("videos" in $$parsedSource) {
            $$parsedSource["videos"] = $$createField0_0($$parsedSource["videos"]);
        }
        return new UnionListResp(/** @type {Partial<UnionListResp>} */($$parsedSource));
    }
}

export class VideoDetailReq {
    /**
     * Creates a new VideoDetailReq instance.
     * @param {Partial<VideoDetailReq>} [$$source = {}] - The source object to create the VideoDetailReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vod_id"] = "";
        }
        if (!("refresh" in $$source)) {
            /**
             * 为 true 时先从源站拉取最新数据再返回
             * @member
             * @type {boolean}
             */
            this["refresh"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoDetailReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoDetailReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoDetailReq(/** @type {Partial<VideoDetailReq>} */($$parsedSource));
    }
}

export class VideoDetailResp {
    /**
     * Creates a new VideoDetailResp instance.
     * @param {Partial<VideoDetailResp>} [$$source = {}] - The source object to create the VideoDetailResp.
     */
    constructor($$source = {}) {
        if (!("video" in $$source)) {
            /**
             * @member
             * @type {model$0.Video | null}
             */
            this["video"] = null;
        }
        if (!("episodes" in $$source)) {
            /**
             * @member
             * @type {(model$0.Episode | null)[]}
             */
            this["episodes"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(model$0.PlayLine | null)[] | undefined}
             */
            this["lines"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {detail$0.Error | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoDetailResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoDetailResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType29;
        const $$createField3_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("video" in $$parsedSource) {
            $$parsedSource["video"] = $$createField0_0($$parsedSource["video"]);
        }
        if ("episodes" in $$parsedSource) {
            $$parsedSource["episodes"] = $$createField1_0($$parsedSource["episodes"]);
        }
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField2_0($$parsedSource["lines"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField3_0($$parsedSource["error"]);
        }
        return new VideoDetailResp(/** @type {Partial<VideoDetailResp>} */($$parsedSource));
    }
}

export class VideoListReq {
    /**
     * Creates a new VideoListReq instance.
     * @param {Partial<VideoListReq>} [$$source = {}] - The source object to create the VideoListReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("recent_days" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["recent_days"] = 0;
        }
        if (!("type_id" in $$source)) {
            /**
             * type_id 同时支持字符串与数字，保存为字符串
             * @member
             * @type {string}
             */
            this["type_id"] = "";
        }
        if (!("year" in $$source)) {
            /**
             * 年份筛选（"all" 或具体年份）
             * @member
             * @type {string}
             */
            this["year"] = "";
        }
        if (!("area" in $$source)) {
            /**
             * 地区筛选（"all" 或具体地区）
             * @member
             * @type {string}
             */
            this["area"] = "";
        }
        if (!("keyword" in $$source)) {
            /**
             * 关键词：标题/演员/导演/备注/年份/地区/类型 模糊匹配
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }
        if (!("sort" in $$source)) {
            /**
             * "" 默认; "rating" 按评分; "hot" 按热度
             * @member
             * @type {string}
             */
            this["sort"] = "";
        }
        if (!("cursor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cursor"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoListReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoListReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoListReq(/** @type {Partial<VideoListReq>} */($$parsedSource));
    }
}

export class VideoListResp {
    /**
     * Creates a new VideoListResp instance.
     * @param {Partial<VideoListResp>} [$$source = {}] - The source object to create the VideoListResp.
     */
    constructor($$source = {}) {
        if (!("videos" in $$source)) {
            /**
             * @member
             * @type {(model$0.Video | null)[]}
             */
            this["videos"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("next_cursor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["next_cursor"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * LocalVideos carries catalog-only matches the upstream search missed,
             * e.g. "是，大臣" for keyword "大臣" when the source API matches prefixes.
             * @member
             * @type {(model$0.Video | null)[] | undefined}
             */
            this["local_videos"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoListResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoListResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType14;
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("videos" in $$parsedSource) {
            $$parsedSource["videos"] = $$createField0_0($$parsedSource["videos"]);
        }
        if ("local_videos" in $$parsedSource) {
            $$parsedSource["local_videos"] = $$createField3_0($$parsedSource["local_videos"]);
        }
        return new VideoListResp(/** @type {Partial<VideoListResp>} */($$parsedSource));
    }
}

export class VideoSearchReq {
    /**
     * Creates a new VideoSearchReq instance.
     * @param {Partial<VideoSearchReq>} [$$source = {}] - The source object to create the VideoSearchReq.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("keyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyword"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoSearchReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoSearchReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoSearchReq(/** @type {Partial<VideoSearchReq>} */($$parsedSource));
    }
}

/**
 * YearAreaResp 前端用于前端：返回所有可选年份 / 地区列表（用于筛选下拉框的选项）
 */
export class YearsResp {
    /**
     * Creates a new YearsResp instance.
     * @param {Partial<YearsResp>} [$$source = {}] - The source object to create the YearsResp.
     */
    constructor($$source = {}) {
        if (!("years" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["years"] = [];
        }
        if (!("areas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["areas"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new YearsResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {YearsResp}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("years" in $$parsedSource) {
            $$parsedSource["years"] = $$createField0_0($$parsedSource["years"]);
        }
        if ("areas" in $$parsedSource) {
            $$parsedSource["areas"] = $$createField1_0($$parsedSource["areas"]);
        }
        return new YearsResp(/** @type {Partial<YearsResp>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = db$0.MergeCandidate.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = PlayLineSpeedItem.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = db$0.RecycleItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = SourceScheduleItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = model$0.Video.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = SourceTableSummary.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = model$0.Episode.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = SourceParamDoc.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = db$0.TableColumn.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = db$0.UnionVideo.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = model$0.PlayLine.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = detail$0.Error.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
