// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as x509$0 from "../x509/models.js";

/**
 * ConnectionState records basic TLS details about the connection.
 */
export class ConnectionState {
    /**
     * Creates a new ConnectionState instance.
     * @param {Partial<ConnectionState>} [$$source = {}] - The source object to create the ConnectionState.
     */
    constructor($$source = {}) {
        if (!("Version" in $$source)) {
            /**
             * Version is the TLS version used by the connection (e.g. VersionTLS12).
             * @member
             * @type {number}
             */
            this["Version"] = 0;
        }
        if (!("HandshakeComplete" in $$source)) {
            /**
             * HandshakeComplete is true if the handshake has concluded.
             * @member
             * @type {boolean}
             */
            this["HandshakeComplete"] = false;
        }
        if (!("DidResume" in $$source)) {
            /**
             * DidResume is true if this connection was successfully resumed from a
             * previous session with a session ticket or similar mechanism.
             * @member
             * @type {boolean}
             */
            this["DidResume"] = false;
        }
        if (!("CipherSuite" in $$source)) {
            /**
             * CipherSuite is the cipher suite negotiated for the connection (e.g.
             * TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_AES_128_GCM_SHA256).
             * @member
             * @type {number}
             */
            this["CipherSuite"] = 0;
        }
        if (!("CurveID" in $$source)) {
            /**
             * CurveID is the key exchange mechanism used for the connection. The name
             * refers to elliptic curves for legacy reasons, see [CurveID]. If a legacy
             * RSA key exchange is used, this value is zero.
             * @member
             * @type {CurveID}
             */
            this["CurveID"] = CurveID.$zero;
        }
        if (!("NegotiatedProtocol" in $$source)) {
            /**
             * NegotiatedProtocol is the application protocol negotiated with ALPN.
             * @member
             * @type {string}
             */
            this["NegotiatedProtocol"] = "";
        }
        if (!("NegotiatedProtocolIsMutual" in $$source)) {
            /**
             * NegotiatedProtocolIsMutual used to indicate a mutual NPN negotiation.
             * 
             * Deprecated: this value is always true.
             * @member
             * @type {boolean}
             */
            this["NegotiatedProtocolIsMutual"] = false;
        }
        if (!("ServerName" in $$source)) {
            /**
             * ServerName is the value of the Server Name Indication extension sent by
             * the client. It's available both on the server and on the client side.
             * @member
             * @type {string}
             */
            this["ServerName"] = "";
        }
        if (!("PeerCertificates" in $$source)) {
            /**
             * PeerCertificates are the parsed certificates sent by the peer, in the
             * order in which they were sent. The first element is the leaf certificate
             * that the connection is verified against.
             * 
             * On the client side, it can't be empty. On the server side, it can be
             * empty if Config.ClientAuth is not RequireAnyClientCert or
             * RequireAndVerifyClientCert.
             * 
             * PeerCertificates and its contents should not be modified.
             * @member
             * @type {(x509$0.Certificate | null)[]}
             */
            this["PeerCertificates"] = [];
        }
        if (!("VerifiedChains" in $$source)) {
            /**
             * VerifiedChains is a list of one or more chains where the first element is
             * PeerCertificates[0] and the last element is from Config.RootCAs (on the
             * client side) or Config.ClientCAs (on the server side).
             * 
             * On the client side, it's set if Config.InsecureSkipVerify is false. On
             * the server side, it's set if Config.ClientAuth is VerifyClientCertIfGiven
             * (and the peer provided a certificate) or RequireAndVerifyClientCert.
             * 
             * VerifiedChains and its contents should not be modified.
             * @member
             * @type {(x509$0.Certificate | null)[][]}
             */
            this["VerifiedChains"] = [];
        }
        if (!("SignedCertificateTimestamps" in $$source)) {
            /**
             * SignedCertificateTimestamps is a list of SCTs provided by the peer
             * through the TLS handshake for the leaf certificate, if any.
             * @member
             * @type {string[]}
             */
            this["SignedCertificateTimestamps"] = [];
        }
        if (!("OCSPResponse" in $$source)) {
            /**
             * OCSPResponse is a stapled Online Certificate Status Protocol (OCSP)
             * response provided by the peer for the leaf certificate, if any.
             * @member
             * @type {string}
             */
            this["OCSPResponse"] = "";
        }
        if (!("TLSUnique" in $$source)) {
            /**
             * TLSUnique contains the "tls-unique" channel binding value (see RFC 5929,
             * Section 3). This value will be nil for TLS 1.3 connections and for
             * resumed connections that don't support Extended Master Secret (RFC 7627).
             * @member
             * @type {string}
             */
            this["TLSUnique"] = "";
        }
        if (!("ECHAccepted" in $$source)) {
            /**
             * ECHAccepted indicates if Encrypted Client Hello was offered by the client
             * and accepted by the server. Currently, ECH is supported only on the
             * client side.
             * @member
             * @type {boolean}
             */
            this["ECHAccepted"] = false;
        }
        if (!("HelloRetryRequest" in $$source)) {
            /**
             * HelloRetryRequest indicates whether we sent a HelloRetryRequest if we
             * are a server, or if we received a HelloRetryRequest if we are a client.
             * @member
             * @type {boolean}
             */
            this["HelloRetryRequest"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionState}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType4;
        const $$createField11_0 = $Create.ByteSlice;
        const $$createField12_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PeerCertificates" in $$parsedSource) {
            $$parsedSource["PeerCertificates"] = $$createField8_0($$parsedSource["PeerCertificates"]);
        }
        if ("VerifiedChains" in $$parsedSource) {
            $$parsedSource["VerifiedChains"] = $$createField9_0($$parsedSource["VerifiedChains"]);
        }
        if ("SignedCertificateTimestamps" in $$parsedSource) {
            $$parsedSource["SignedCertificateTimestamps"] = $$createField10_0($$parsedSource["SignedCertificateTimestamps"]);
        }
        if ("OCSPResponse" in $$parsedSource) {
            $$parsedSource["OCSPResponse"] = $$createField11_0($$parsedSource["OCSPResponse"]);
        }
        if ("TLSUnique" in $$parsedSource) {
            $$parsedSource["TLSUnique"] = $$createField12_0($$parsedSource["TLSUnique"]);
        }
        return new ConnectionState(/** @type {Partial<ConnectionState>} */($$parsedSource));
    }
}

/**
 * CurveID is the type of a TLS identifier for a key exchange mechanism. See
 * https://www.iana.org/assignments/tls-parameters/tls-parameters.xml#tls-parameters-8.
 * 
 * In TLS 1.2, this registry used to support only elliptic curves. In TLS 1.3,
 * it was extended to other groups and renamed NamedGroup. See RFC 8446, Section
 * 4.2.7. It was then also extended to other mechanisms, such as hybrid
 * post-quantum KEMs.
 * @readonly
 * @enum {number}
 */
export const CurveID = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    CurveP256: 23,
    CurveP384: 24,
    CurveP521: 25,
    X25519: 29,
    X25519MLKEM768: 4588,
    SecP256r1MLKEM768: 4587,
    SecP384r1MLKEM1024: 4589,
};

// Private type creation functions
const $$createType0 = x509$0.Certificate.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.ByteSlice);
