// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstallReport 是热替换脚本的回执，连同此刻真正在运行的版本号。
 * 界面照它说话：Result 为空表示这次启动没拿到任何回执（首次安装、或上次没装过更新）。
 */
export class InstallReport {
    /**
     * Creates a new InstallReport instance.
     * @param {Partial<InstallReport>} [$$source = {}] - The source object to create the InstallReport.
     */
    constructor($$source = {}) {
        if (!("result" in $$source)) {
            /**
             * Result 取 ok / swap_failed / verify_failed / rollback_ok / rollback_failed。
             * @member
             * @type {string}
             */
            this["result"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["running"] = "";
        }
        if (!("failed" in $$source)) {
            /**
             * Failed 为真表示这次更新没换成：界面该给一句"现在还是旧版本"，而不是沉默。
             * @member
             * @type {boolean}
             */
            this["failed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstallReport}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallReport(/** @type {Partial<InstallReport>} */($$parsedSource));
    }
}

/**
 * PendingInstall 是「退出时安装」这个入口此刻的现场情况，直接给界面显示用。
 * 
 * 这里报的是「安排了什么」，不是「装上了没有」——兑现发生在进程最后一次收尾时刻，
 * 那次成没成由脚本的回执在下次启动说话（见 LastInstallReport）。
 */
export class PendingInstall {
    /**
     * Creates a new PendingInstall instance.
     * @param {Partial<PendingInstall>} [$$source = {}] - The source object to create the PendingInstall.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingInstall instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PendingInstall}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PendingInstall(/** @type {Partial<PendingInstall>} */($$parsedSource));
    }
}

/**
 * RollbackInfo 是「退回上一版」这个入口此刻的现场情况。
 * 
 * 只有文件大小和时间，没有版本号：副本就是 exe 旁边那个 .old 文件，没有任何地方
 * 记着它是从哪个版本抄来的。宁可让用户看时间自己判断，不可在这里编一个版本号出来。
 */
export class RollbackInfo {
    /**
     * Creates a new RollbackInfo instance.
     * @param {Partial<RollbackInfo>} [$$source = {}] - The source object to create the RollbackInfo.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("size_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_bytes"] = 0;
        }
        if (!("modified_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modified_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RollbackInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RollbackInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RollbackInfo(/** @type {Partial<RollbackInfo>} */($$parsedSource));
    }
}
