// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as textproto$0 from "../../net/textproto/models.js";

/**
 * A FileHeader describes a file part of a multipart request.
 */
export class FileHeader {
    /**
     * Creates a new FileHeader instance.
     * @param {Partial<FileHeader>} [$$source = {}] - The source object to create the FileHeader.
     */
    constructor($$source = {}) {
        if (!("Filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Filename"] = "";
        }
        if (!("Header" in $$source)) {
            /**
             * @member
             * @type {textproto$0.MIMEHeader}
             */
            this["Header"] = {};
        }
        if (!("Size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileHeader instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileHeader}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Header" in $$parsedSource) {
            $$parsedSource["Header"] = $$createField1_0($$parsedSource["Header"]);
        }
        return new FileHeader(/** @type {Partial<FileHeader>} */($$parsedSource));
    }
}

/**
 * Form is a parsed multipart form.
 * Its File parts are stored either in memory or on disk,
 * and are accessible via the [*FileHeader]'s Open method.
 * Its Value parts are stored as strings.
 * Both are keyed by field name.
 */
export class Form {
    /**
     * Creates a new Form instance.
     * @param {Partial<Form>} [$$source = {}] - The source object to create the Form.
     */
    constructor($$source = {}) {
        if (!("Value" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["Value"] = {};
        }
        if (!("File" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: (FileHeader | null)[] }}
             */
            this["File"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Form instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Form}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Value" in $$parsedSource) {
            $$parsedSource["Value"] = $$createField0_0($$parsedSource["Value"]);
        }
        if ("File" in $$parsedSource) {
            $$parsedSource["File"] = $$createField1_0($$parsedSource["File"]);
        }
        return new Form(/** @type {Partial<Form>} */($$parsedSource));
    }
}

// Private type creation functions
var $$createType0 = /** @type {(...args: any[]) => any} */(function $$initCreateType0(...args) {
    if ($$createType0 === $$initCreateType0) {
        $$createType0 = $$createType2;
    }
    return $$createType0(...args);
});
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = FileHeader.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType5);
