#!/usr/bin/env python3
"""生成 app/douban/t2s_table.go 里的繁→简单字对照表。

数据来源是 pip 包 zhconv 自带的 OpenCC/Unihan 派生字典（zhcdict.json 的 zh2Hans）。
那份字典按短语消歧，所以只剩「单字对单字」的条目天然不含 乾/著/瞭 这类需要上下文
才能定形的字——正是我们做标题归一化时唯一敢用的子集。

用法（需要能装包的网络）：
    pip install zhconv
    python scripts/gen_t2s_table.py
"""

import json
import os
import sys

try:
    import zhconv.zhconv as z
except ImportError:  # pragma: no cover
    sys.exit("需要 zhconv：pip install zhconv")

HAN_START, HAN_END = 0x3400, 0x9FFF


def is_han(ch: str) -> bool:
    return len(ch) == 1 and HAN_START <= ord(ch) <= HAN_END


def load():
    path = os.path.join(os.path.dirname(z.__file__), "zhcdict.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def build_pairs(data):
    trad_only = set(data.get("TRADONLY", ""))
    simp_only = set(data.get("SIMPONLY", ""))
    pairs = []
    for src, dst in data["zh2Hans"].items():
        if not (is_han(src) and is_han(dst)) or src == dst:
            continue
        # 只留「繁体侧确实只在传统文本里出现、简体侧不是繁体专用字」的映射，
        # 双向都站得住才说明这是一次字符繁简折叠，而不是词义替换。
        if src in simp_only or dst in trad_only:
            continue
        pairs.append((src, dst))
    pairs.sort(key=lambda p: (ord(p[0]), ord(p[1])))
    return pairs


def render(pairs) -> str:
    chunks = []
    buf = []
    for src, dst in pairs:
        buf.append(src + dst)
        if len(buf) == 12:
            chunks.append("".join(buf))
            buf = []
    if buf:
        chunks.append("".join(buf))
    # Go 没有续行符：常量必须从同一行的 "" 开始，每行以 + 结尾，最后一行不带 +。
    body = "\n\t".join('"' + c + '" +' for c in chunks[:-1])
    body += '\n\t"' + chunks[-1] + '"'
    return (
        "// Code generated by scripts/gen_t2s_table.py; DO NOT EDIT BY HAND.\n"
        "// 重新生成：pip install zhconv && python scripts/gen_t2s_table.py\n"
        "package douban\n"
        "\n"
        "// traditionalSimplifiedPairs 繁→简单字对照，按「繁,简」两字一组紧挨着排，\n"
        "// 长度必为偶数；非法条目（自映射、奇数长度）由 title_norm_test.go 兜底。\n"
        'const traditionalSimplifiedPairs = "" +\n\t' + body + "\n"
    )


def main():
    data = load()
    pairs = build_pairs(data)
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "app", "douban", "t2s_table.go")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(pairs))
    print(f"wrote {len(pairs)} pairs -> {out}")
    for probe in "發後裡麵乾著瞭":
        print(" check", probe, "->", dict(pairs).get(probe, "(omitted)"))


if __name__ == "__main__":
    main()
