// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Error {
    /**
     * Creates a new Error instance.
     * @param {Partial<Error>} [$$source = {}] - The source object to create the Error.
     */
    constructor($$source = {}) {
        if (!("source_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_key"] = "";
        }
        if (!("global_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["global_id"] = 0;
        }
        if (!("source_vod_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_vod_id"] = "";
        }
        if (!("attempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempts"] = 0;
        }
        if (!("retryable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["retryable"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Error instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Error}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Error(/** @type {Partial<Error>} */($$parsedSource));
    }
}
