// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DoubanInfo {
    /**
     * Creates a new DoubanInfo instance.
     * @param {Partial<DoubanInfo>} [$$source = {}] - The source object to create the DoubanInfo.
     */
    constructor($$source = {}) {
        if (!("SubjectID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SubjectID"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Rating" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Rating"] = "";
        }
        if (!("Votes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Votes"] = "";
        }
        if (!("Director" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Director"] = "";
        }
        if (!("Writer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Writer"] = "";
        }
        if (!("Actor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Actor"] = "";
        }
        if (!("Genre" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Genre"] = "";
        }
        if (!("Country" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Country"] = "";
        }
        if (!("Language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Language"] = "";
        }
        if (!("ReleaseDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ReleaseDate"] = "";
        }
        if (!("SeasonCount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SeasonCount"] = "";
        }
        if (!("EpisodeCount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EpisodeCount"] = "";
        }
        if (!("Duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Duration"] = "";
        }
        if (!("Aka" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Aka"] = "";
        }
        if (!("IMDb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["IMDb"] = "";
        }
        if (!("PosterURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PosterURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoubanInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoubanInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoubanInfo(/** @type {Partial<DoubanInfo>} */($$parsedSource));
    }
}
