// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Record 是一条已落盘日志的结构化视图，字段顺序与文件行格式一一对应。
 */
export class Record {
    /**
     * Creates a new Record instance.
     * @param {Partial<Record>} [$$source = {}] - The source object to create the Record.
     */
    constructor($$source = {}) {
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }
        if (!("ts" in $$source)) {
            /**
             * unix 毫秒
             * @member
             * @type {number}
             */
            this["ts"] = 0;
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("caller" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["caller"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Record}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Record(/** @type {Partial<Record>} */($$parsedSource));
    }
}
